f = open(r"C:\Users\wifik\Downloads\EURUSD!_M5_202301020000_202605061250.csv", "rb")
data = f.read(1000)
f.close()
out = open(r"C:\Users\wifik\Desktop\projects\larger-lab\nautilus\data\check.txt", "w", encoding="utf-8")
out.write("First 1000 bytes:\n")
out.write(str(data))
out.write("\n\nAs text:\n")
out.write(data.decode("utf-8", errors="replace"))
out.close()
