"""QL-EXEC-R1 — generic execution runtime domain contracts and registries.

Pure domain + configuration infrastructure. No broker connection, no broker
orders, no MetaTrader5, no strategy science, no Capital Routing math.
"""
from __future__ import annotations

from .account import AccountObservedState, AccountProfile
from .authority import (
    ExecutionAuthorityDecision,
    authentication_satisfied,
    derive_execution_authority,
    identity_gate,
    requires_identity_verification,
    requires_secret,
)
from .binding import StrategyAccountBinding
from .brokers import MT5BrokerSession
from .capabilities import BrokerCapabilities
from .compatibility import CompatibilityState, evaluate_compatibility
from .enums import (
    AccountRole,
    AuthenticationMode,
    BrokerErrorCategory,
    CapabilityState,
    ClockStatus,
    CompatibilityStatus,
    DesiredState,
    Environment,
    ExecutionMode,
    ExecutionTransport,
    FillPolicy,
    HedgingNetting,
    MachineProfile,
    MarketStatus,
    OrderSide,
    OrderType,
    OwnershipMode,
    QuantityUnit,
    ReservationState,
    RoutingDecision,
    RuntimeHealth,
    SecretKind,
    SlippageUnit,
)
from .hashing import canonical_json, canonicalize, config_hash
from .interfaces import (
    BrokerSession,
    CapitalPolicyAdapter,
    CapitalTranslationAdapter,
    StrategyAdapter,
)
from .ownership import (
    BrokerOwnershipTag,
    LogicalOwnershipId,
    OwnershipNamespace,
    encode_broker_ownership,
    magic_for_namespace,
)
from .portfolio import PortfolioGroup
from .profiles import (
    RuntimeObservedState,
    RuntimePaths,
    RuntimeProfile,
    RuntimeState,
    assert_no_path_collision,
    build_runtime_paths,
    canonical_runtime_id,
    normalize_runtime_id,
    validate_runtime_id,
)
from .registry import (
    AccountRegistry,
    BindingRegistry,
    PortfolioGroupRegistry,
    RuntimeProfileRegistry,
)
from .reservation import (
    ReservationRecord,
    reservation_id_for,
    validate_reservation_transition,
)
from .routing import AccountRouter, RoutingResult
from .types import (
    AccountState,
    Bar,
    BoundAccountSnapshot,
    BrokerAdapterId,
    BrokerClockState,
    BrokerCompanyId,
    BrokerIdentity,
    BrokerSnapshot,
    CancelResult,
    CapitalDecision,
    CapitalRequest,
    CheckResult,
    CloseResult,
    Deal,
    EconomicTarget,
    InstrumentTarget,
    MarketReference,
    Order,
    OrderIntent,
    OrderResult,
    Position,
    SecretReference,
    StrategyEvent,
    StrategyExposureContext,
    SubmitResult,
    SymbolInfo,
    Tick,
)

__all__ = [
    "AccountObservedState",
    "AccountProfile",
    "AccountRegistry",
    "AccountRole",
    "AccountRouter",
    "AccountState",
    "AuthenticationMode",
    "Bar",
    "BindingRegistry",
    "BoundAccountSnapshot",
    "BrokerAdapterId",
    "BrokerCapabilities",
    "BrokerClockState",
    "BrokerErrorCategory",
    "BrokerCompanyId",
    "BrokerIdentity",
    "BrokerOwnershipTag",
    "BrokerSession",
    "BrokerSnapshot",
    "CancelResult",
    "CapabilityState",
    "CapitalDecision",
    "CapitalPolicyAdapter",
    "CapitalRequest",
    "CapitalTranslationAdapter",
    "CheckResult",
    "ClockStatus",
    "CloseResult",
    "CompatibilityState",
    "CompatibilityStatus",
    "Deal",
    "DesiredState",
    "EconomicTarget",
    "Environment",
    "ExecutionAuthorityDecision",
    "ExecutionMode",
    "ExecutionTransport",
    "FillPolicy",
    "HedgingNetting",
    "InstrumentTarget",
    "LogicalOwnershipId",
    "MachineProfile",
    "MarketReference",
    "MarketStatus",
    "MT5BrokerSession",
    "Order",
    "OrderIntent",
    "OrderResult",
    "OrderSide",
    "OrderType",
    "OwnershipMode",
    "OwnershipNamespace",
    "PortfolioGroup",
    "PortfolioGroupRegistry",
    "Position",
    "ReservationRecord",
    "ReservationState",
    "RoutingDecision",
    "RoutingResult",
    "QuantityUnit",
    "RuntimeHealth",
    "RuntimeObservedState",
    "RuntimePaths",
    "RuntimeProfile",
    "RuntimeProfileRegistry",
    "RuntimeState",
    "SecretKind",
    "SecretReference",
    "SlippageUnit",
    "StrategyAccountBinding",
    "StrategyAdapter",
    "StrategyEvent",
    "StrategyExposureContext",
    "SubmitResult",
    "SymbolInfo",
    "Tick",
    "assert_no_path_collision",
    "authentication_satisfied",
    "build_runtime_paths",
    "canonical_json",
    "canonical_runtime_id",
    "canonicalize",
    "config_hash",
    "derive_execution_authority",
    "encode_broker_ownership",
    "evaluate_compatibility",
    "identity_gate",
    "magic_for_namespace",
    "normalize_runtime_id",
    "requires_identity_verification",
    "requires_secret",
    "reservation_id_for",
    "validate_reservation_transition",
    "validate_runtime_id",
]
