"""OCE mandatory test registry (B2-R8, extended for B3).

Single source of truth for the mandatory test registry, category
assignment, expected per-category totals, and the required evidence
artifact list. Generated from ACTUAL pytest collection by
scripts/gen_mandatory_registry.py (B3-R8). The gate fails if the
collected total differs from this registry — adding a test requires
a deliberate regeneration in the same change.
"""

SCHEMA_VERSION = "2.1.0"
VALIDATOR_VERSION = "2.1.0"
EXPECTED_REPO = "dabiggestpoppa/larger-lab"
EXPECTED_BRANCH = "oce-program-build"

REQUIRED_ARTIFACTS = [
    "source-identity.json",
    "tool-versions.json",
    "migration-results.json",
    "test-registry.json",
    "junit.xml",
    "pytest-output.txt",
    "unit-results.json",
    "postgres-integration-results.json",
    "redis-integration-results.json",
    "scheduler-results.json",
    "worker-results.json",
    "api-results.json",
    "po-hermes-boundary-results.json",
    "adversarial-results.json",
    "local-lifecycle-results.json",
    "validation-regression-results.json",
    "worker-fabric-core-results.json",
    "worker-supervisor-results.json",
    "sandbox-resource-results.json",
    "representative-job-results.json",
    "cli-lifecycle-results.json",
    "outbound-session-results.json",
    "end-to-end-job-results.json",
    "fabric-pg-results.json",
    "source-cleanliness.json",
    "cleanup-results.json",
    "independent-gate.json",
    "stage-status.json",
    "stage-log.txt",
    "evidence-manifest.json",
    "validation-summary.md",
]

ARTIFACT_CATEGORY_FILE = {
    "unit": "unit-results.json",
    "postgres": "postgres-integration-results.json",
    "redis": "redis-integration-results.json",
    "scheduler": "scheduler-results.json",
    "worker": "worker-results.json",
    "api": "api-results.json",
    "po-hermes-boundary": "po-hermes-boundary-results.json",
    "adversarial": "adversarial-results.json",
    "local-lifecycle": "local-lifecycle-results.json",
    "validation-regression": "validation-regression-results.json",
    "worker-fabric-core": "worker-fabric-core-results.json",
    "worker-supervisor": "worker-supervisor-results.json",
    "sandbox-resource": "sandbox-resource-results.json",
    "representative-job": "representative-job-results.json",
    "cli-lifecycle": "cli-lifecycle-results.json",
    "outbound-session": "outbound-session-results.json",
    "end-to-end-job": "end-to-end-job-results.json",
    "fabric-pg": "fabric-pg-results.json",
}

MANDATORY_TEST_IDS = [
    "infrastructure.control-plane.tests.test_api_read_auth::test_health_and_readiness_need_no_grant",
    "infrastructure.control-plane.tests.test_api_read_auth::test_inspect_requires_read_grant_after_submit",
    "infrastructure.control-plane.tests.test_api_read_auth::test_read_denials_are_recorded",
    "infrastructure.control-plane.tests.test_api_read_auth::test_read_endpoints_allowed_with_read_grant",
    "infrastructure.control-plane.tests.test_api_read_auth::test_read_endpoints_denied_without_grant",
    "infrastructure.control-plane.tests.test_api_read_auth::test_submit_grant_does_not_authorize_reads",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_capability_escalation_refused",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_concurrent_duplicate_claim_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_duplicate_result_detected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_forbidden_env_var_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_forbidden_executable_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_forged_lease_token_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_forged_worker_identity_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_hermes_cannot_perform_po_only_action",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_late_result_quarantined",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_mismatched_result_hash_detected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_oversized_artifact_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_partial_upload_has_no_visible_artifact",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_path_traversal_blocked",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_process_crash_is_retryable_then_dl",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_retry_exhaustion_dead_letters",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_revoked_credential_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_stale_fencing_generation_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_unknown_capability_fails_closed",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_unsupported_protocol_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_wrong_credential_rejected",
    "infrastructure.control-plane.tests.test_b3_adversarial.TestAdversarialFabric::test_wrong_trust_zone_fails_closed",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestFabricAdversarialClosure::test_forbidden_exec_env_path",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestFabricAdversarialClosure::test_forged_fence_and_late_result",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestFabricAdversarialClosure::test_mismatched_hash_and_oversized_partial",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestFailureEvidencePropagation::test_run_id_guard_and_expected_repo",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestFailureEvidencePropagation::test_runner_steps_capture_cleanliness_and_source",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestFailureEvidencePropagation::test_write_failure_evidence_hashes_all_files",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestHermesBoundaryReal::test_hermes_cannot_authorized_retry_dead_letter",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestHermesBoundaryReal::test_hermes_is_not_operator_po",
    "infrastructure.control-plane.tests.test_b3_adversarial_closure.TestHermesBoundaryReal::test_retry_coordinator_persists_durable_dead_letter",
    "infrastructure.control-plane.tests.test_b3_end_to_end_jobs::test_artifacts_survive_control_plane_restart",
    "infrastructure.control-plane.tests.test_b3_end_to_end_jobs::test_duplicate_delivery_one_material_effect",
    "infrastructure.control-plane.tests.test_b3_end_to_end_jobs::test_end_to_end_representative_jobs",
    "infrastructure.control-plane.tests.test_b3_end_to_end_jobs::test_lease_expiry_and_reclaim",
    "infrastructure.control-plane.tests.test_b3_end_to_end_jobs::test_po_authorized_retry_records_audit_and_hermes_denied",
    "infrastructure.control-plane.tests.test_b3_end_to_end_jobs::test_revoked_worker_refused",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_service::test_capability_escalation_rejected",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_service::test_full_outbound_path_with_separate_worker_process",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_service::test_revoked_worker_rejected",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_units::test_action_signature_scoped_to_session_and_action",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_units::test_client_and_server_proof_are_identical",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_units::test_wire_key_is_double_hash_not_identity_verifier",
    "infrastructure.control-plane.tests.test_b3_outbound_protocol_units::test_wrong_secret_proof_never_matches",
    "infrastructure.control-plane.tests.test_b3_representative_jobs::test_cancellation_during_execution",
    "infrastructure.control-plane.tests.test_b3_representative_jobs::test_representative_safe_job_full_path",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_admission_is_po_only",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_cleanup_preserves_configuration",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_configure_does_not_admit",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_configure_then_admit_then_start_across_processes",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_repeated_cap_parsed_as_list",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_revocation_persists_across_processes",
    "infrastructure.control-plane.tests.test_b3_worker_cli_lifecycle.TestCliLifecycle::test_stale_pid_detected_never_signalled",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_capability_admission_is_persisted_and_per_operator",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_drain_rejects_new_work_through_store",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_effect_registered_once",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_expired_lease_reclaimed",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_identity_persisted_and_verifier_hashed",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_late_result_quarantined_durably",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_lease_claim_fence_and_reclaim",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_manifest_persisted_and_reloaded_on_restart",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_monotonic_fence_generation_after_reclaim",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_retry_state_dead_letter_and_po_authorized_retry",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_revoked_identity_refused",
    "infrastructure.control-plane.tests.test_b3_worker_fabric_store_integration::test_session_created_and_heartbeated",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_denial_recorded",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_expired_grant_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_hermes_blocked_from_po_actions",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_high_risk_requires_approval",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_idempotency_replay_detected",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_issue_grant_succeeds",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_missing_grant_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_revoked_grant_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_self_approval_blocked",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_verify_grant_succeeds",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_wrong_action_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestAuthorityEngine::test_wrong_target_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestJobStore::test_conflicting_idempotency_keys",
    "infrastructure.control-plane.tests.test_control_plane.TestJobStore::test_duplicate_job_submission_idempotent",
    "infrastructure.control-plane.tests.test_control_plane.TestJobStore::test_invalid_lifecycle_transition_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestJobStore::test_job_transition_legal",
    "infrastructure.control-plane.tests.test_control_plane.TestJobStore::test_submit_job_succeeds",
    "infrastructure.control-plane.tests.test_control_plane.TestJobStore::test_unauthorized_job_submission_denied",
    "infrastructure.control-plane.tests.test_control_plane.TestStateMachines::test_artifact_transitions",
    "infrastructure.control-plane.tests.test_control_plane.TestStateMachines::test_grant_transitions",
    "infrastructure.control-plane.tests.test_control_plane.TestStateMachines::test_illegal_transition_raises",
    "infrastructure.control-plane.tests.test_control_plane.TestStateMachines::test_job_transitions_illegal",
    "infrastructure.control-plane.tests.test_control_plane.TestStateMachines::test_job_transitions_legal",
    "infrastructure.control-plane.tests.test_control_plane.TestStateMachines::test_terminal_states",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_abandoned_work_recovered",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_duplicate_delivery_protection",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_expired_lease_blocks_result",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_lease_renewal",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_stale_worker_cannot_commit",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_worker_admit_and_claim",
    "infrastructure.control-plane.tests.test_control_plane.TestWorkerLeases::test_wrong_worker_cannot_complete",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_cas_idempotency",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_duplicate_result_single_provenance",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_manifest_verify_and_read",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_partial_upload_tmp_cleaned",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_restart_safe_manifest_reload",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_size_enforcement",
    "infrastructure.control-plane.tests.test_execution_runtime.TestArtifactStore::test_tampered_artifact_detected",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_allowed_executable_ok",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_cleanup_removes_workspaces",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_forbidden_env_var_rejected",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_forbidden_executable_fails_closed",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_fresh_workspace_per_attempt",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_output_size_limit",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_path_escape_blocked",
    "infrastructure.control-plane.tests.test_execution_runtime.TestBoundedRunner::test_timeout_enforced",
    "infrastructure.control-plane.tests.test_execution_runtime.TestRetryCoordinator::test_backoff_deterministic",
    "infrastructure.control-plane.tests.test_execution_runtime.TestRetryCoordinator::test_classification",
    "infrastructure.control-plane.tests.test_execution_runtime.TestRetryCoordinator::test_operator_authorized_retry",
    "infrastructure.control-plane.tests.test_execution_runtime.TestRetryCoordinator::test_retry_exhaustion",
    "infrastructure.control-plane.tests.test_execution_runtime.TestRetryCoordinator::test_success_has_one_material_effect",
    "infrastructure.control-plane.tests.test_execution_runtime.TestRetryCoordinator::test_terminal_no_retry_and_dead_letter",
    "infrastructure.control-plane.tests.test_execution_runtime.TestSandboxB3R5::test_cancel_current_terminates_in_flight_run",
    "infrastructure.control-plane.tests.test_execution_runtime.TestSandboxB3R5::test_forbidden_cloud_prefix_env_leak_rejected",
    "infrastructure.control-plane.tests.test_execution_runtime.TestSandboxB3R5::test_non_strict_reports_degradation_without_raising",
    "infrastructure.control-plane.tests.test_execution_runtime.TestSandboxB3R5::test_output_extension_allowlist_enforced",
    "infrastructure.control-plane.tests.test_execution_runtime.TestSandboxB3R5::test_preflight_reports_enforced_boundaries_on_posix",
    "infrastructure.control-plane.tests.test_execution_runtime.TestSandboxB3R5::test_strict_mode_blocks_when_isolation_unavailable",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestAPIPermissions::test_api_audit_history",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestAPIPermissions::test_api_inspect_nonexistent_job",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestAPIPermissions::test_api_submit_with_permission",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestAPIPermissions::test_api_submit_without_permission_denied",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestAPIPermissions::test_direct_api_permission_bypass_blocked",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_health_check_healthy",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_no_duplicate_effects_after_recovery",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_pg_unavailable_blocks",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_pg_unavailable_fail_closed",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_recovery_after_restart",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_redis_loss_reconciled",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHealthAndRecovery::test_redis_unavailable_degraded",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHermesBoundary::test_hermes_cannot_perform_po_actions",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHermesBoundary::test_hermes_escalates_capital_request",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHermesBoundary::test_hermes_rate_limiting",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHermesBoundary::test_hermes_receive_request",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestHermesBoundary::test_hermes_routes_to_po_for_oce",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestPOBoundary::test_po_cannot_bypass_environment_lock",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestPOBoundary::test_po_create_work_plan",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestPOBoundary::test_po_escalate_decision",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestPOBoundary::test_po_high_risk_requires_approval",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestPOBoundary::test_po_spawn_subagent",
    "infrastructure.control-plane.tests.test_health_api_boundaries.TestPOBoundary::test_po_submit_permitted_job",
    "infrastructure.control-plane.tests.test_http_api_integration::test_console_served",
    "infrastructure.control-plane.tests.test_http_api_integration::test_every_endpoint_requires_grant",
    "infrastructure.control-plane.tests.test_http_api_integration::test_health_and_readiness_unauthenticated",
    "infrastructure.control-plane.tests.test_http_api_integration::test_invalid_grant_denied_403",
    "infrastructure.control-plane.tests.test_http_api_integration::test_read_endpoints_with_grant",
    "infrastructure.control-plane.tests.test_http_api_integration::test_submit_inspect_cancel_roundtrip",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_bare_port_binding_rejected",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_cloud_credential_hint_detects_cloud_env",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_configure_writes_compose_env_with_secret",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_destroy_removes_volume_only_with_yes",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_destroy_requires_confirmation",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_doctor_reports_cloud_free_when_clean",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_lifecycle_module_never_uses_pkill",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_pid_file_with_garbage_ignored",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_public_bind_rejected",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_real_compose_ports_are_loopback_only",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_require_runtime_dsn_fails_closed_without_secret",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_require_runtime_dsn_prefers_environment",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_secret_file_restrictive_permissions",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_secret_generated_ephemeral_no_predictable_default",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_secret_honors_operator_env",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_stale_dead_pid_cleared_not_signalled",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_start_fails_closed_without_docker",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_stop_terminates_only_pid_file_process",
    "infrastructure.control-plane.tests.test_local_lifecycle::test_unrelated_process_never_signalled",
    "infrastructure.control-plane.tests.test_pg_integration::test_cancel_and_quarantine_persist",
    "infrastructure.control-plane.tests.test_pg_integration::test_exact_replay_returns_same_job",
    "infrastructure.control-plane.tests.test_pg_integration::test_idempotency_key_reuse_by_other_actor_rejected",
    "infrastructure.control-plane.tests.test_pg_integration::test_idempotency_key_reuse_with_changed_payload_rejected",
    "infrastructure.control-plane.tests.test_pg_integration::test_job_persists_and_survives_reconnect",
    "infrastructure.control-plane.tests.test_pg_integration::test_migration_checksum_mismatch_detected",
    "infrastructure.control-plane.tests.test_pg_integration::test_migrations_from_empty_db",
    "infrastructure.control-plane.tests.test_pg_integration::test_pg_unavailable_fails_closed",
    "infrastructure.control-plane.tests.test_pg_integration::test_stale_lease_fenced_on_commit",
    "infrastructure.control-plane.tests.test_pg_integration::test_wrong_lease_token_fenced",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_advisory_lock_prevents_duplicate_firing",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_cancel_removes_schedule_from_pg",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_concurrency_limit_respected",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_delayed_job_fires_after_restart_when_due",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_pause_resume_survive_restart",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_restart_recovery_recomputes_recurring_next_run",
    "infrastructure.control-plane.tests.test_pg_scheduler_integration::test_schedules_persist_and_survive_restart",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_admission_persists_token_hash_not_token",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_admission_requires_token",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_claim_allows_matching_capabilities",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_claim_enforces_required_capabilities",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_claim_requires_valid_token",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_claim_without_required_capabilities_any_worker",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_lease_token_fencing_on_commit",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_reauthmit_with_different_token_rejected",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_recover_abandoned_lease_returns_job_to_pending",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_renew_and_complete_roundtrip",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_revoked_worker_refused_everywhere",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_stale_lease_fenced_on_commit",
    "infrastructure.control-plane.tests.test_pg_worker_integration::test_surrender_then_reclaim",
    "infrastructure.control-plane.tests.test_redis_integration::test_real_redis_notify_and_lease_mirror",
    "infrastructure.control-plane.tests.test_redis_integration::test_reconstruct_from_real_pg",
    "infrastructure.control-plane.tests.test_redis_transport::test_ephemeral_cache_roundtrip",
    "infrastructure.control-plane.tests.test_redis_transport::test_heartbeat_and_worker_alive",
    "infrastructure.control-plane.tests.test_redis_transport::test_lease_mirror_nx_and_ttl",
    "infrastructure.control-plane.tests.test_redis_transport::test_notify_receive_roundtrip",
    "infrastructure.control-plane.tests.test_redis_transport::test_quarantine_roundtrip",
    "infrastructure.control-plane.tests.test_redis_transport::test_rate_check_limit",
    "infrastructure.control-plane.tests.test_redis_transport::test_reconstruct_from_pg_rebuilds_and_quarantines",
    "infrastructure.control-plane.tests.test_redis_transport::test_reconstruct_reports_failure_without_raising",
    "infrastructure.control-plane.tests.test_redis_transport::test_scheduler_wakeup",
    "infrastructure.control-plane.tests.test_redis_transport::test_transport_unavailable_on_downstream_failure",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestEvidenceSystem::test_manifest_built_and_verified",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestEvidenceSystem::test_manifest_tamper_rejected",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestEvidenceSystem::test_missing_artifact_rejected",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestEvidenceSystem::test_replay_reconstructs",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestEvidenceSystem::test_truth_promotion",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestEvidenceSystem::test_truth_promotion_blocked_downward",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_delayed_job_not_ready",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_delayed_job_ready_after_advance",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_duplicate_prevention_same_tick",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_immediate_job_scheduled",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_pause_resume",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_recurring_job",
    "infrastructure.control-plane.tests.test_scheduler_evidence.TestScheduler::test_scheduler_restart_recovery",
    "infrastructure.control-plane.tests.test_schema_validation::test_agent_identity_rejects_wrong_type",
    "infrastructure.control-plane.tests.test_schema_validation::test_agent_identity_validates",
    "infrastructure.control-plane.tests.test_schema_validation::test_capability_grant_validates",
    "infrastructure.control-plane.tests.test_schema_validation::test_denial_envelope_rejects_invalid_reason",
    "infrastructure.control-plane.tests.test_schema_validation::test_denial_envelope_validates",
    "infrastructure.control-plane.tests.test_schema_validation::test_event_envelope_validates",
    "infrastructure.control-plane.tests.test_schema_validation::test_job_envelope_validates",
    "infrastructure.control-plane.tests.test_schema_validation::test_schema_registry_rejects_unknown",
    "infrastructure.control-plane.tests.test_schema_validation::test_schema_registry_validates",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_altered_manifest_content_fails_final_verify",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_dirty_source_after_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_dirty_source_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_duplicate_test_id_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_failing_test_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_failure_evidence_remains_uploadable",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_final_verifier_passes_on_clean_evidence",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_gate_passes_on_clean_evidence",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_migration_failure_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_missing_cleanup_evidence_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_missing_mandatory_test_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_removed_false_makes_gate_fail",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_skipped_container_test_makes_gate_fail_in_ci",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_stage_log_mutation_fails_final_verify",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_stage_status_mismatch_fails_final_verify",
    "infrastructure.control-plane.tests.test_validation_gate_regressions::test_wrong_commit_makes_gate_fail",
    "infrastructure.control-plane.tests.test_worker_admission_units::test_admission_token_hash_is_deterministic",
    "infrastructure.control-plane.tests.test_worker_admission_units::test_capabilities_satisfied",
    "infrastructure.control-plane.tests.test_worker_admission_units::test_invalid_capability_manifest_rejected",
    "infrastructure.control-plane.tests.test_worker_admission_units::test_valid_capability_manifest_passes",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_capability_escalation_refused",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_identity_immutable_and_valid_json",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_supported_protocol_ok",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_unknown_capability_fails_closed",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_unsupported_protocol_fails_closed",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_worker_cannot_self_authorize_without_operator_admission",
    "infrastructure.control-plane.tests.test_worker_fabric.TestContracts::test_wrong_trust_zone_fails_closed",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_atomic_claim_and_monotonic_fence",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_duplicate_delivery_has_one_material_effect",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_forged_lease_token_rejected",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_late_result_quarantined",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_stale_fence_rejected",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_surrender_and_reclaim",
    "infrastructure.control-plane.tests.test_worker_fabric.TestFencedLeases::test_wrong_fence_is_stale_rejection",
    "infrastructure.control-plane.tests.test_worker_fabric.TestOutboundSessions::test_challenge_response_secret_never_transmitted",
    "infrastructure.control-plane.tests.test_worker_fabric.TestOutboundSessions::test_drain_mode_blocks_work",
    "infrastructure.control-plane.tests.test_worker_fabric.TestOutboundSessions::test_duplicate_session_bumps_generation",
    "infrastructure.control-plane.tests.test_worker_fabric.TestOutboundSessions::test_revocation_kills_sessions",
    "infrastructure.control-plane.tests.test_worker_fabric.TestOutboundSessions::test_session_expiration",
    "infrastructure.control-plane.tests.test_worker_fabric.TestOutboundSessions::test_unsupported_protocol_rejected_at_admission",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_cleanup_preserves_artifacts_and_pid_state",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_configure_and_po_admit",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_doctor_warns_on_no_admitted_workers",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_operator_view_shows_fabric_state",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_revoke_drops_admission_and_sessions",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_stale_pid_detected",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_start_stop_runtime_owned_pid",
    "infrastructure.control-plane.tests.test_worker_supervisor.TestSupervisor::test_worker_cannot_self_authorize",
]

_CATEGORY_RULES = [
    ("test_pg_integration", "postgres"),
    ("test_redis_integration", "redis"),
    ("test_pg_scheduler_integration", "scheduler"),
    ("test_pg_worker_integration", "worker"),
    ("test_http_api_integration", "api"),
    ("test_b3_adversarial", "adversarial"),
    ("test_b3_adversarial_closure", "adversarial"),
    ("test_b3_representative_jobs", "representative-job"),
    ("test_execution_runtime", "sandbox-resource"),
    ("test_worker_fabric", "worker-fabric-core"),
    ("test_worker_supervisor", "worker-supervisor"),
    ("test_local_lifecycle", "local-lifecycle"),
    ("test_validation_gate_regressions", "validation-regression"),
    ("test_b3_worker_cli_lifecycle", "cli-lifecycle"),
    ("test_b3_outbound_protocol_units", "outbound-session"),
    ("test_b3_outbound_protocol_service", "outbound-session"),
    ("test_b3_end_to_end_jobs", "end-to-end-job"),
    ("test_b3_worker_fabric_store_integration", "fabric-pg"),
    (".TestPOBoundary::", "po-hermes-boundary"),
    (".TestHermesBoundary::", "po-hermes-boundary"),
]

def category_of(node_id):
    """Deterministic category for a canonical (junit-form) node id."""
    for sub, cat in _CATEGORY_RULES:
        if sub in node_id:
            return cat
    return "unit"

def expected_counts():
    """Expected per-category totals derived from the mandatory registry."""
    counts = {}
    for nid in MANDATORY_TEST_IDS:
        counts[category_of(nid)] = counts.get(category_of(nid), 0) + 1
    return counts

def validate_registry():
    """Fail closed if the registry is malformed (duplicates/unassignable)."""
    from collections import Counter
    dupes = [n for n, c in Counter(MANDATORY_TEST_IDS).items() if c > 1]
    if dupes:
        raise AssertionError('duplicate mandatory ids: %s' % dupes)
    unknown = {c for c in expected_counts() if c not in ARTIFACT_CATEGORY_FILE}
    if unknown:
        raise AssertionError("categories missing results file: %s" % sorted(unknown))
    return expected_counts()

if __name__ == "__main__":
    counts = validate_registry()
    print("registry OK: %d mandatory tests, %d categories" % (sum(counts.values()), len(counts)))
    for c in sorted(counts):
        print("  %-24s %d" % (c, counts[c]))

