#!/usr/bin/env python3
"""
DMR Daily Report Generator
Run at 5 PM EST daily via cron.
Checks: script health, trades, errors, account status.
Generates a brief and saves to quant-lab/reports/
"""
import sqlite3
import json
from datetime import datetime, timezone, timedelta
from pathlib import Path

BASE_DIR = Path(r"C:\Users\wifik\Desktop\projects\larger-lab\quant-lab\mt5")
DB_FILE = BASE_DIR / "dmr_live.db"
STATE_FILE = BASE_DIR / "dmr_live_state.json"
CONFIG_FILE = BASE_DIR / "dmr_config.json"
REPORTS_DIR = Path(r"C:\Users\wifik\Desktop\projects\larger-lab\quant-lab\reports")
REPORTS_DIR.mkdir(exist_ok=True)

def est_now():
    utc_now = datetime.now(timezone.utc)
    est_h = (utc_now.hour - 5 + 24) % 24
    return est_h, utc_now

def query_db(query, params=()):
    if not DB_FILE.exists():
        return []
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute(query, params)
    rows = [dict(r) for r in c.fetchall()]
    conn.close()
    return rows

def generate_report():
    est_h, now = est_now()
    today = now.date().isoformat()
    
    # Load state
    state = {}
    if STATE_FILE.exists():
        with open(STATE_FILE) as f:
            state = json.load(f)
    
    # Load config
    config = {}
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            config = json.load(f)
    
    # Query today's data
    trades_today = query_db("SELECT * FROM trades WHERE date = ? ORDER BY id", (today,))
    p90_today = query_db("SELECT * FROM p90_events WHERE date = ? ORDER BY id", (today,))
    errors_today = query_db("SELECT * FROM system_log WHERE date(timestamp) = ? AND level = 'ERROR' ORDER BY id", (today,))
    
    # All-time stats
    all_trades = query_db("SELECT COUNT(*) as cnt, SUM(CASE WHEN result='W' THEN 1 ELSE 0 END) as wins, SUM(pnl_usd) as total_pnl FROM trades WHERE result != 'OPEN'")
    total_trades = all_trades[0] if all_trades else {'cnt': 0, 'wins': 0, 'total_pnl': 0}
    
    # P90 summary for today
    p90_count = len(p90_today)
    trades_placed = len([t for t in trades_today if t.get('result') == 'OPEN' or t.get('result') in ('W', 'L')])
    wins = len([t for t in trades_today if t.get('result') == 'W'])
    losses = len([t for t in trades_today if t.get('result') == 'L'])
    pnl = sum(t.get('pnl_usd', 0) for t in trades_today)
    
    # Build report
    report = f"""# DMR Daily Report — {today}
Generated: {now.strftime('%Y-%m-%d %H:%M')} UTC ({est_h}:00 EST)

## Today's Summary
| Metric | Value |
|--------|-------|
| P90s Detected | {p90_count} |
| Trades Placed | {trades_placed} |
| Wins | {wins} |
| Losses | {losses} |
| PnL | ${pnl:.2f} |
| Active Symbols | {', '.join(config.get('symbols', []))} |
| Lot Size | {config.get('lot_size', 'N/A')} |
| Trading Enabled | {config.get('enabled', 'N/A')} |

## All-Time Stats
| Metric | Value |
|--------|-------|
| Total Trades | {total_trades.get('cnt', 0)} |
| Total Wins | {total_trades.get('wins', 0)} |
| Total PnL | ${total_trades.get('total_pnl', 0):.2f} |
| Win Rate | {(total_trades.get('wins', 0) / total_trades.get('cnt', 1) * 100):.1f}% |

## P90 Events Today
"""
    if p90_today:
        for p in p90_today:
            report += f"- {p['time'][:16]} | {p['symbol']} | {p['direction']} | Body: {p['body_pips']:.1f}p | Trade: {'YES' if p['trade_triggered'] else 'NO'}\n"
    else:
        report += "- No P90 events recorded\n"
    
    report += f"\n## Trades Today\n"
    if trades_today:
        for t in trades_today:
            report += f"- {t['time'][:16]} | {t['symbol']} | {t['direction']} | {t['result']} | ${t.get('pnl_usd', 0):.2f} | {t.get('notes', '')}\n"
    else:
        report += "- No trades recorded\n"
    
    report += f"\n## Errors Today ({len(errors_today)})\n"
    if errors_today:
        for e in errors_today:
            report += f"- {e['timestamp'][:16]} | [{e['category']}] {e['message']}\n"
    else:
        report += "- No errors ✅\n"
    
    report += f"\n## System State\n"
    report += f"- Date: {state.get('today', 'N/A')}\n"
    if state.get('symbols'):
        for sym, s in state['symbols'].items():
            report += f"- {sym}: P90s={s.get('p90_count',0)}, Trades={s.get('trade_count',0)}, PnL=${s.get('pnl',0):.2f}\n"
    
    report += f"\n---\n_Report generated by DMR Daily Monitor_\n"
    
    # Save report
    report_path = REPORTS_DIR / f"DMR_DAILY_{today}.md"
    with open(report_path, 'w') as f:
        f.write(report)
    
    print(f"Report saved: {report_path}")
    print(report)
    return report

if __name__ == "__main__":
    generate_report()
