"""Shared Foundry vocabularies.

These enums are the single source of truth for role, rights, contamination,
tier, lifecycle, reproducibility, and terminal-state vocabularies. MF-B0
constitutional artifacts and the MF-B1..B4 implementations both bind to this
module so that no block can quietly invent a second vocabulary for the same
concept.

``UNKNOWN`` is a first-class member everywhere it appears. It is never
normalized into a favorable state.
"""

from __future__ import annotations

from enum import StrEnum


class SourceRole(StrEnum):
    """MF-B0.C3.S1 / MF-B2 role state machine. No default role is TRAIN."""

    UNASSIGNED = "UNASSIGNED"
    TRAIN_CPT = "TRAIN_CPT"
    TRAIN_SFT = "TRAIN_SFT"
    TRAIN_PREFERENCE = "TRAIN_PREFERENCE"
    DEV = "DEV"
    DEV_EVAL = "DEV_EVAL"
    PUBLIC_EVAL = "PUBLIC_EVAL"
    PROMOTION_EVAL = "PROMOTION_EVAL"
    HIDDEN_EVAL = "HIDDEN_EVAL"
    SEALED_CONFIRMATION = "SEALED_CONFIRMATION"
    BLIND_DISCOVERY = "BLIND_DISCOVERY"
    RETRIEVAL_ONLY = "RETRIEVAL_ONLY"
    QUARANTINED = "QUARANTINED"
    EXCLUDED = "EXCLUDED"


TRAIN_ROLES = frozenset(
    {SourceRole.TRAIN_CPT, SourceRole.TRAIN_SFT, SourceRole.TRAIN_PREFERENCE}
)
EVAL_ROLES = frozenset(
    {
        SourceRole.DEV,
        SourceRole.DEV_EVAL,
        SourceRole.PUBLIC_EVAL,
        SourceRole.PROMOTION_EVAL,
        SourceRole.HIDDEN_EVAL,
        SourceRole.SEALED_CONFIRMATION,
    }
)
# Roles that may not be packed into a training dataset.
NON_TRAIN_ROLES = frozenset(
    {
        SourceRole.UNASSIGNED,
        SourceRole.RETRIEVAL_ONLY,
        SourceRole.QUARANTINED,
        SourceRole.EXCLUDED,
    }
    | EVAL_ROLES
)


class RightsState(StrEnum):
    """MF-B0.C3.S2 / CON-MF-10. Observed facts are separate from policy."""

    RIGHTS_VERIFIED_BY_POLICY = "RIGHTS_VERIFIED_BY_POLICY"
    RIGHTS_RESTRICTED = "RIGHTS_RESTRICTED"
    RIGHTS_UNKNOWN = "RIGHTS_UNKNOWN"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    EXCLUDED_BY_POLICY = "EXCLUDED_BY_POLICY"


TRAIN_PERMISSIVE_RIGHTS = frozenset({RightsState.RIGHTS_VERIFIED_BY_POLICY})


class RightsBasis(StrEnum):
    """Observed/provided basis of a rights decision (not itself permission)."""

    EXPLICIT_OPEN_LICENSE = "EXPLICIT_OPEN_LICENSE"
    PUBLIC_DOMAIN = "PUBLIC_DOMAIN"
    OPERATOR_OWNED = "OPERATOR_OWNED"
    PROVIDER_TERMS_ALLOW = "PROVIDER_TERMS_ALLOW"
    DIRECT_PERMISSION = "DIRECT_PERMISSION"
    RIGHTS_REVIEW_REQUIRED = "RIGHTS_REVIEW_REQUIRED"
    UNKNOWN = "UNKNOWN"
    PROHIBITED = "PROHIBITED"


class ContaminationClass(StrEnum):
    """MF-B0.C3.S3 graded contamination. C0 + C5 != proven clean."""

    C0_NO_OBSERVED_OVERLAP = "C0_NO_OBSERVED_OVERLAP"
    C1_SOURCE_FAMILY_PROXIMITY = "C1_SOURCE_FAMILY_PROXIMITY"
    C2_SEMANTIC_TASK_PROXIMITY = "C2_SEMANTIC_TASK_PROXIMITY"
    C3_PARAPHRASE_OR_SOLUTION_OVERLAP = "C3_PARAPHRASE_OR_SOLUTION_OVERLAP"
    C4_DIRECT_ITEM_OR_ANSWER_OVERLAP = "C4_DIRECT_ITEM_OR_ANSWER_OVERLAP"
    C5_UPSTREAM_PROVENANCE_UNKNOWN = "C5_UPSTREAM_PROVENANCE_UNKNOWN"


CONTAMINATION_SEVERITY: dict[ContaminationClass, int] = {
    ContaminationClass.C0_NO_OBSERVED_OVERLAP: 0,
    ContaminationClass.C5_UPSTREAM_PROVENANCE_UNKNOWN: 1,
    ContaminationClass.C1_SOURCE_FAMILY_PROXIMITY: 2,
    ContaminationClass.C2_SEMANTIC_TASK_PROXIMITY: 3,
    ContaminationClass.C3_PARAPHRASE_OR_SOLUTION_OVERLAP: 4,
    ContaminationClass.C4_DIRECT_ITEM_OR_ANSWER_OVERLAP: 5,
}

# Classes strong enough to force a benchmark lifecycle downgrade.
CLAIM_DEGRADING_CONTAMINATION = frozenset(
    {
        ContaminationClass.C3_PARAPHRASE_OR_SOLUTION_OVERLAP,
        ContaminationClass.C4_DIRECT_ITEM_OR_ANSWER_OVERLAP,
    }
)


class ContaminationType(StrEnum):
    """MF-B2 typed relationship vocabulary (finer grained than the C-scale)."""

    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    NEAR_DUPLICATE = "NEAR_DUPLICATE"
    PARAPHRASE_OR_DERIVATIVE = "PARAPHRASE_OR_DERIVATIVE"
    SAME_ANSWER_TEMPLATE = "SAME_ANSWER_TEMPLATE"
    BENCHMARK_DISCUSSION = "BENCHMARK_DISCUSSION"
    SOLUTION_EXPOSURE = "SOLUTION_EXPOSURE"
    SOURCE_FAMILY_OVERLAP = "SOURCE_FAMILY_OVERLAP"
    MODEL_GENERATED_FROM_EXPOSED_MODEL = "MODEL_GENERATED_FROM_EXPOSED_MODEL"
    RETRIEVAL_EXPOSURE = "RETRIEVAL_EXPOSURE"
    CONTEXT_EXPOSURE = "CONTEXT_EXPOSURE"
    UNKNOWN_ANCESTRY = "UNKNOWN_ANCESTRY"

    @property
    def severity(self) -> ContaminationClass:
        return _TYPE_TO_CLASS[self]


_TYPE_TO_CLASS: dict[ContaminationType, ContaminationClass] = {
    ContaminationType.EXACT_DUPLICATE: ContaminationClass.C4_DIRECT_ITEM_OR_ANSWER_OVERLAP,
    ContaminationType.NEAR_DUPLICATE: ContaminationClass.C3_PARAPHRASE_OR_SOLUTION_OVERLAP,
    ContaminationType.PARAPHRASE_OR_DERIVATIVE: ContaminationClass.C3_PARAPHRASE_OR_SOLUTION_OVERLAP,
    ContaminationType.SAME_ANSWER_TEMPLATE: ContaminationClass.C3_PARAPHRASE_OR_SOLUTION_OVERLAP,
    ContaminationType.BENCHMARK_DISCUSSION: ContaminationClass.C2_SEMANTIC_TASK_PROXIMITY,
    ContaminationType.SOLUTION_EXPOSURE: ContaminationClass.C4_DIRECT_ITEM_OR_ANSWER_OVERLAP,
    ContaminationType.SOURCE_FAMILY_OVERLAP: ContaminationClass.C1_SOURCE_FAMILY_PROXIMITY,
    ContaminationType.MODEL_GENERATED_FROM_EXPOSED_MODEL: ContaminationClass.C3_PARAPHRASE_OR_SOLUTION_OVERLAP,
    ContaminationType.RETRIEVAL_EXPOSURE: ContaminationClass.C2_SEMANTIC_TASK_PROXIMITY,
    ContaminationType.CONTEXT_EXPOSURE: ContaminationClass.C2_SEMANTIC_TASK_PROXIMITY,
    ContaminationType.UNKNOWN_ANCESTRY: ContaminationClass.C5_UPSTREAM_PROVENANCE_UNKNOWN,
}


class EvaluationTier(StrEnum):
    """MF-B0.C2.S2 / MF-B4. No result may upgrade its own tier."""

    DEVELOPMENT = "DEVELOPMENT"
    PROMOTION = "PROMOTION"
    SEALED_CONFIRMATION = "SEALED_CONFIRMATION"


TIER_RANK: dict[EvaluationTier, int] = {
    EvaluationTier.DEVELOPMENT: 0,
    EvaluationTier.PROMOTION: 1,
    EvaluationTier.SEALED_CONFIRMATION: 2,
}


class ClaimClass(StrEnum):
    """MF-B0.C4.S2 — CEREBUS reconstruction claim classes."""

    BLIND_TASK_PERFORMANCE = "BLIND_TASK_PERFORMANCE"
    CONTROLLED_INDEPENDENT_REDISCOVERY = "CONTROLLED_INDEPENDENT_REDISCOVERY"
    POST_REVEAL_REPRODUCTION = "POST_REVEAL_REPRODUCTION"


CLAIM_CLASS_RANK: dict[ClaimClass, int] = {
    ClaimClass.POST_REVEAL_REPRODUCTION: 0,
    ClaimClass.BLIND_TASK_PERFORMANCE: 1,
    ClaimClass.CONTROLLED_INDEPENDENT_REDISCOVERY: 2,
}


class ReproducibilityClass(StrEnum):
    """MF-B0.C6.S1 levels."""

    R0_EXACT_REPLAY = "R0_EXACT_REPLAY"
    R1_FRESH_ENVIRONMENT_REPLAY = "R1_FRESH_ENVIRONMENT_REPLAY"
    R2_INDEPENDENT_IMPLEMENTATION = "R2_INDEPENDENT_IMPLEMENTATION"
    R3_EXTERNAL_DOMAIN_REPLICATION = "R3_EXTERNAL_DOMAIN_REPLICATION"


class ComputeReproducibility(StrEnum):
    """MF-B1 typed reproducibility for compute runs."""

    ENVIRONMENT_REPRODUCIBLE = "ENVIRONMENT_REPRODUCIBLE"
    FUNCTIONALLY_REPRODUCIBLE = "FUNCTIONALLY_REPRODUCIBLE"
    STATISTICALLY_REPRODUCIBLE = "STATISTICALLY_REPRODUCIBLE"
    NONREPRODUCIBLE = "NONREPRODUCIBLE"


class RunState(StrEnum):
    """MF-B0.C9.S2 experiment/run lifecycle."""

    PLANNED = "PLANNED"
    FROZEN = "FROZEN"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    UNDERPOWERED = "UNDERPOWERED"
    OPERATOR_HOLD = "OPERATOR_HOLD"


class ArtifactLifecycleState(StrEnum):
    REGISTERED = "REGISTERED"
    BASELINED = "BASELINED"
    EXPERIMENTAL = "EXPERIMENTAL"
    DOMAIN_VALIDATED = "DOMAIN_VALIDATED"
    DORMANT = "DORMANT"
    REJECTED = "REJECTED"
    REOPENED = "REOPENED"


class BenchmarkStatus(StrEnum):
    """MF-B4 §13 / MF-B0.C9.S4."""

    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    FROZEN = "FROZEN"
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    COMPROMISED = "COMPROMISED"
    SATURATED = "SATURATED"
    STALE = "STALE"
    RETIRED = "RETIRED"


class CapabilityEvidenceState(StrEnum):
    UNASSESSED = "UNASSESSED"
    MEASURED = "MEASURED"
    REPRODUCED = "REPRODUCED"
    READY_FOR_OCE_CAPABILITY_REVIEW = "READY_FOR_OCE_CAPABILITY_REVIEW"


class ComputeFailure(StrEnum):
    """MF-B1 §9 failure taxonomy."""

    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    CAPACITY_UNAVAILABLE = "CAPACITY_UNAVAILABLE"
    ENVIRONMENT_MISMATCH = "ENVIRONMENT_MISMATCH"
    OOM = "OOM"
    PREEMPTED = "PREEMPTED"
    STORAGE_FAILURE = "STORAGE_FAILURE"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    CHECKPOINT_FAILURE = "CHECKPOINT_FAILURE"
    FRAMEWORK_INCOMPATIBLE = "FRAMEWORK_INCOMPATIBLE"
    BUDGET_BLOCKED = "BUDGET_BLOCKED"
    SECURITY_BLOCKED = "SECURITY_BLOCKED"
    UNKNOWN_RESOURCE_FAILURE = "UNKNOWN_RESOURCE_FAILURE"


class RefineryFailure(StrEnum):
    """MF-B3 §15 failure taxonomy."""

    SOURCE_UNRESOLVED = "SOURCE_UNRESOLVED"
    RIGHTS_BLOCKED = "RIGHTS_BLOCKED"
    PARSE_FAILED = "PARSE_FAILED"
    LOSSY_TRANSFORM_UNACCEPTABLE = "LOSSY_TRANSFORM_UNACCEPTABLE"
    DUPLICATE_COLLAPSED = "DUPLICATE_COLLAPSED"
    CONTAMINATION_BLOCKED = "CONTAMINATION_BLOCKED"
    PARTITION_LEAKAGE = "PARTITION_LEAKAGE"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    PIT_INVALID = "PIT_INVALID"
    SYNTHETIC_LINEAGE_MISSING = "SYNTHETIC_LINEAGE_MISSING"
    MANIFEST_MISMATCH = "MANIFEST_MISMATCH"
    UNKNOWN_DATA_FAILURE = "UNKNOWN_DATA_FAILURE"


class ExposureType(StrEnum):
    """MF-B4 §12 exposure ledger."""

    USED_IN_TRAINING = "USED_IN_TRAINING"
    USED_IN_SFT = "USED_IN_SFT"
    USED_FOR_CHECKPOINT_SELECTION = "USED_FOR_CHECKPOINT_SELECTION"
    VIEWED_BY_BUILDER_AGENT = "VIEWED_BY_BUILDER_AGENT"
    VIEWED_BY_EVALUATOR_AUTHORING_MODEL = "VIEWED_BY_EVALUATOR_AUTHORING_MODEL"
    RETRIEVED_DURING_TASK = "RETRIEVED_DURING_TASK"
    PUBLISHED_PUBLICLY = "PUBLISHED_PUBLICLY"
    LEAKED_THROUGH_SYNTHETIC_DATA = "LEAKED_THROUGH_SYNTHETIC_DATA"
    ACCESSED_SEALED_PAYLOAD = "ACCESSED_SEALED_PAYLOAD"


COMPROMISING_EXPOSURES = frozenset(
    {
        ExposureType.USED_IN_TRAINING,
        ExposureType.USED_IN_SFT,
        ExposureType.USED_FOR_CHECKPOINT_SELECTION,
        ExposureType.VIEWED_BY_BUILDER_AGENT,
        ExposureType.VIEWED_BY_EVALUATOR_AUTHORING_MODEL,
        ExposureType.PUBLISHED_PUBLICLY,
        ExposureType.LEAKED_THROUGH_SYNTHETIC_DATA,
        ExposureType.ACCESSED_SEALED_PAYLOAD,
    }
)

EXPOSURE_BUDGET_BY_TIER: dict[EvaluationTier, int] = {
    EvaluationTier.DEVELOPMENT: 10_000,
    EvaluationTier.PROMOTION: 25,
    EvaluationTier.SEALED_CONFIRMATION: 3,
}


class SubjectKind(StrEnum):
    """MF-B0.C1.S3 / MF-B4 §4 — three distinct evaluation subjects."""

    COGNITIVE_ARTIFACT = "COGNITIVE_ARTIFACT"
    COGNITIVE_RUNTIME = "COGNITIVE_RUNTIME"
    COGNITIVE_SYSTEM = "COGNITIVE_SYSTEM"


class IdentityDimension(StrEnum):
    """Dimensions of artifact/runtime/system identity (AMB-MF-01)."""

    WEIGHTS = "WEIGHTS"
    INPUT_ENCODER = "INPUT_ENCODER"
    QUANTIZATION = "QUANTIZATION"
    INFERENCE_ENGINE = "INFERENCE_ENGINE"
    STATE_SEMANTICS = "STATE_SEMANTICS"
    PROMPT_SCAFFOLD = "PROMPT_SCAFFOLD"
    RETRIEVAL_CORPUS = "RETRIEVAL_CORPUS"
    TOOL_SCAFFOLD = "TOOL_SCAFFOLD"


class TerminalConclusion(StrEnum):
    """MF-B0.C2.S4 legally available conclusions. There is no forced PASS."""

    PASS = "PASS"
    FAIL = "FAIL"
    UNDERPOWERED = "UNDERPOWERED"
    INCONCLUSIVE = "INCONCLUSIVE"
    DATA_BLOCKED = "DATA_BLOCKED"
    COMPUTE_BLOCKED = "COMPUTE_BLOCKED"
    RIGHTS_BLOCKED = "RIGHTS_BLOCKED"
    CONTAMINATED = "CONTAMINATED"
    PROTOCOL_VIOLATION = "PROTOCOL_VIOLATION"
    OPERATOR_HOLD = "OPERATOR_HOLD"


class TrustClass(StrEnum):
    """MF-B0.C7.S1 / MF-B1 §5."""

    PUBLIC_RESEARCH = "PUBLIC_RESEARCH"
    LICENSED_NONPUBLIC = "LICENSED_NONPUBLIC"
    PRIVATE_OPERATOR = "PRIVATE_OPERATOR"
    SECRET_BEARING_PROHIBITED_REMOTE = "SECRET_BEARING_PROHIBITED_REMOTE"
    SEALED_EVAL = "SEALED_EVAL"


REMOTE_INADMISSIBLE_TRUST = frozenset(
    {
        TrustClass.SECRET_BEARING_PROHIBITED_REMOTE,
        TrustClass.SEALED_EVAL,
    }
)
