from __future__ import annotations
from pathlib import Path
import pandas as pd, numpy as np
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
import lf4_common as C

def main():
 r=C.RESULTS
 # Pre-event paths are intentionally unavailable from the event-only cache.
 pd.DataFrame([{"peer_family":"rank25/50/100","coverage":"available same-date rank context only","status":"VALID"},{"peer_family":"behavioral","coverage":0,"status":"DATA_BLOCKED"},{"peer_family":"correlation","coverage":0,"status":"DATA_BLOCKED"},{"peer_family":"state","coverage":0,"status":"DATA_BLOCKED"}]).to_csv(r/"10_NEIGHBOR_PRE_EVENT_PATHS.csv",index=False)
 pd.DataFrame(columns=["peer_family","horizon","n","peer_median_return","peer_breadth","peer_dispersion","status"]).to_csv(r/"11_NEIGHBOR_POST_EVENT_PATHS.csv",index=False) if not (r/"11_NEIGHBOR_POST_EVENT_PATHS.csv").exists() else None
 pd.DataFrame([{"model_block":"M0_event","cv_auc":np.nan,"status":"DESCRIPTIVE_ONLY"},{"model_block":"M1_neighbor","cv_auc":np.nan,"status":"DATA_BLOCKED_BEHAVIORAL_PEERS"},{"model_block":"M2_health","cv_auc":np.nan,"status":"DATA_BLOCKED_FUTURE_RANK_HEALTH"},{"model_block":"M3_global","cv_auc":np.nan,"status":"DESCRIPTIVE_ONLY"}]).to_csv(r/"13_LONELY_DUMP_MODEL_BLOCKS.csv",index=False)
 # Re-run descriptive quality summaries as explicit sequence table.
 pd.DataFrame([{ "sequence":"RANK_ONLY_ISOLATED -> forward recovery","n":int(len(pd.read_csv(r/"04_ALL_LONER_OUTCOMES.csv"))),"periods":np.nan,"lift":np.nan,"status":"DESCRIPTIVE_ONLY_NO_PURGED_SEQUENCE_TEST"}]).to_csv(r/"28_LOCAL_SEQUENCE_ATLAS.csv",index=False)
 pd.DataFrame([
 {"node":"RANK_CONTEXT_ISOLATION","verdict":"LOCAL_NODE","effect":"same-date rank context is reproducible; true behavioral/correlation peers unavailable","statistical_validity":"VALID_DESCRIPTIVE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"},
 {"node":"PRICE_RECOVERY_VS_RANK_HEALTH","verdict":"DATA_BLOCKED","effect":"future rank history absent from LF2 event cache","statistical_validity":"NOT_ESTIMABLE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"},
 {"node":"ISOLATED_DOWN_REVERSAL","verdict":"PROMOTION_CANDIDATE_WITH_LIMITATIONS","effect":"retained as LF2/LF3 descriptive node; LF4 peer attribution not established","statistical_validity":"DESCRIPTIVE_REPLICATION","executability_status":"NOT_YET_AUDITED","possible_expression":"SPOT_LONG_OR_PERP_LONG_UNKNOWN"},
 {"node":"BREADTH_DISP_TAIL","verdict":"DESCRIPTIVE_ONLY","effect":"repaired triangle is associational; no mediation/synergy claim","statistical_validity":"DESCRIPTIVE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"},
 {"node":"ACTIVE_LIQUIDITY","verdict":"DESCRIPTIVE_ONLY","effect":"volume quintile anatomy without joint controlled model","statistical_validity":"DESCRIPTIVE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"},
 {"node":"SHHM_VS_SHMC","verdict":"LOCAL_NODE","effect":"one focused recheck; no causal or executable interpretation","statistical_validity":"DESCRIPTIVE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"}]).to_csv(r/"29_PROMOTE_MERGE_DISSOLVE.csv",index=False)
 pd.DataFrame([
 {"result":"behavioral nearest-neighbor map","status":"DATA_BLOCKED","reason":"cache lacks complete PIT feature set required for pre-event matching"},
 {"result":"correlation nearest-neighbor map","status":"DATA_BLOCKED","reason":"no trailing return matrix in supplied cache"},
 {"result":"state-neighbor map","status":"DATA_BLOCKED","reason":"complete state/liquidity buckets unavailable"},
 {"result":"future rank-health clocks","status":"DATA_BLOCKED","reason":"event cache contains pre-event rank velocity but not future rank observations"},
 {"result":"true contagion direction","status":"DATA_BLOCKED","reason":"peer maps unavailable"},
 {"result":"LF3 basket dispersion","status":"DISSOLVE_PRIOR_ARTIFACT","reason":"LF4 rebuild uses finite same-date raw returns"},
 {"result":"triangle high conditional values","status":"DISSOLVE_PRIOR_LABELING","reason":"repaired output labels correlations and residual variance ratios explicitly"}]).to_csv(r/"30_NULL_AND_FAILED_RESULTS.csv",index=False)
 pd.DataFrame([
 {"node":"ISOLATED_DOWN_REVERSAL","role":"REVERSAL / DISTRIBUTION","sample":"LF2/LF3 event families","effect":"rank- and sign-dependent descriptive reversal","confidence":"moderate with limitations","conditionality":"rank, sign, participation","rank_scope":"501-2000","time_scope":"1-30D","causal_level":"L0/L1","failure_modes":"overlap, peer attribution unavailable","statistical_validity":"DESCRIPTIVE_REPLICATION","executability_status":"NOT_YET_AUDITED","possible_expression":"SPOT_LONG_OR_PERP_LONG_UNKNOWN"},
 {"node":"RANK_CONTEXT_ISOLATION","role":"LOCAL_CLUSTER / DISTRIBUTION","sample":"same-date rank neighbors","effect":"separate rank-context coordinate","confidence":"moderate","conditionality":"rank window","rank_scope":"501-2000","time_scope":"event day","causal_level":"L0","failure_modes":"wrong-neighbor risk","statistical_validity":"DESCRIPTIVE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"},
 {"node":"TOP500_BREADTH_GATE","role":"CROSS_FIELD_GATE / REGIME_FILTER","sample":"LF2/LF3","effect":"higher realization under high breadth","confidence":"moderate","conditionality":"common-factor controls in parent work","rank_scope":"501-2000","time_scope":"event-time","causal_level":"L1 candidate","failure_modes":"lag ambiguity, no MECH-8 join","statistical_validity":"PARENT_REPLICATION","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"},
 {"node":"PRICE_RANK_SEPARATION","role":"RANK_HEALTH / DECAY_CONTEXT","sample":"not estimable","effect":"queued","confidence":"none","conditionality":"future rank history required","rank_scope":"501-2000","time_scope":"3-30D","causal_level":"DATA_BLOCKED","failure_modes":"missing future ranks","statistical_validity":"NOT_ESTIMABLE","executability_status":"NOT_YET_AUDITED","possible_expression":"UNKNOWN"}]).to_csv(r/"31_ALPHA_ROLE_REGISTRY.csv",index=False)
 pd.DataFrame([
 {"claim":"same-date asset/rank neighbor co-movement","level":"L0_DESCRIPTIVE_CO_MOVEMENT","basis":"contemporaneous rank-window context"},
 {"claim":"isolated shock forward reversal","level":"L1_TEMPORAL_ORDERING","basis":"event precedes forward observation; no causal mechanism"},
 {"claim":"Top500 breadth to lower delivery","level":"L1_CANDIDATE_ONLY","basis":"parent lag/conditioning evidence; LF4 does not upgrade"},
 {"claim":"behavioral/correlation peer attribution","level":"DATA_BLOCKED","basis":"required PIT peer maps unavailable"},
 {"claim":"price recovery causes rank recovery","level":"NOT_SUPPORTED","basis":"future rank observations unavailable"}]).to_csv(r/"22_CAUSALITY_LADDER.csv",index=False)
 (r.parent/"32_LOWER_FIELD_4_SUMMARY.md").write_text("""# LOWER-FIELD-4 SUMMARY\n\nLF4 was designed to replace same-band isolation with true PIT peer geometry. The available LF2 cache supports a valid same-date rank-neighbor map (±25/±50/±100), but it does not contain a complete historical feature matrix or trailing-return matrix for behavioral and correlation nearest neighbors. Those families are therefore DATA_BLOCKED, not silently approximated.\n\nThe reproducible event universe contains 1,023 primary isolated downside observations at |z1|>=2 in the LF3 event table. Rank-context isolation is a valid descriptive coordinate. It cannot establish whether a supposed loner is a true behavioral loner, whether peers catch down, or whether the asset rebounds toward peers.\n\nLF2/LF3 reversal geometry remains a parent finding: isolated downside events show sign- and depth-dependent forward reversal patterns. LF4 does not overclaim peer attribution because the required peer maps are unavailable. Price-recovery versus rank-health clocks are DATA_BLOCKED: the cache provides pre-event rank velocity, not future rank observations.\n\nThe LF3 basket dispersion anomaly is not reused. LF4 rebuilds dispersion from finite same-date raw returns, and the triangle output is relabeled as Pearson correlations and residual variance ratios; prior near-one unlabeled values are not treated as conditional probabilities.\n\nVolume/active-liquidity and HH anatomy are descriptive only without the requested joint purged models. SHHM versus SHMC receives one focused descriptive recheck. No strategy, PnL, directional signal, execution, or deployment claim is made.\n\n## Node disposition\n- PROMOTION_CANDIDATE_WITH_LIMITATIONS: parent isolated-down reversal, pending true-peer remeasurement.\n- LOCAL_NODE: rank-context isolation; SHHM/SHMC descriptive distinction.\n- DESCRIPTIVE_ONLY: repaired basket and breadth-dispersion-tail triangle.\n- DATA_BLOCKED: behavioral/correlation/state neighbors, peer contagion direction, price-versus-rank health clocks.\n- DISSOLVE_PRIOR_ARTIFACT: LF3 absurd basket dispersion and mislabeled triangle near-one values.\n\n`human_review_required=TRUE`; `next_checkpoint_authorized=FALSE`.\n""",encoding="utf-8")
 (r.parent/"33_LOWER_FIELD_4_DECISION.md").write_text("""# LOWER-FIELD-4 DECISION\n\n**Decision:** `PASS_LOWER_FIELD_4_WITH_LIMITATIONS`\n\n**Integrity:** rank-neighbor and repaired basket/triangle outputs are finite and schema-checked.\n\n**Hard limitation:** this checkpoint does not earn a TRUE_NEAREST_NEIGHBOR promotion. Behavioral, correlation, state, peer-aftermath, and future rank-health analyses are `DATA_BLOCKED` because the available LF2 cache lacks the required PIT histories/matrices.\n\n**Adjudication:**\n- `PROMOTION_CANDIDATE_WITH_LIMITATIONS`: isolated-down reversal as an inherited descriptive node; true peer attribution remains open.\n- `LOCAL_NODE`: rank-context isolation.\n- `DESCRIPTIVE_ONLY`: active liquidity, HH anatomy, SHHM/SHMC, rebuilt basket geometry, triangle.\n- `DISSOLVE`: prior LF3 basket dispersion values and ambiguous near-one triangle labels.\n- `DATA_BLOCKED`: behavioral/correlation/state peer maps, false-loner truth, contagion direction, price/rank clocks, controlled outcome models.\n\nAll causality remains L0/L1. `STATISTICAL_VALIDITY` and `EXECUTABILITY_STATUS=NOT_YET_AUDITED` remain separate.\n\n`human_review_required=TRUE`\n`next_checkpoint_authorized=FALSE`\n""",encoding="utf-8")
 print('finalized')
if __name__=='__main__':main()
