"""SENSOR-B4-I03 — adversarial blob-store tests: crash matrix, races, order.

Commit-sequence I03C seal surface (I03 §38-§41, §61, §63-§65, §74-§75):

- staging isolation: a partial stage NEVER appears as a valid final object,
  and an adversarial concurrent reader can never observe half-written final
  bytes;
- deterministic crash/fault matrix A-F (injected fault hooks, no killed
  runner) with the machine-readable `BLOC_04_I03_CRASH_MATRIX.json`
  regenerated by tests — never hand-declared;
- canonical durable-operation order contract, including the machine-readable
  `BLOC_04_I03_ATOMIC_ORDER.json`;
- concurrent identical writers (publish race) and concurrent distinct
  writers (no crosstalk);
- cross-filesystem atomic commit DENIAL (dependency-injected device probe,
  no CI second mount required);
- long-component denial BEFORE any artifact write (final key AND
  caller-supplied staging identity).
"""

from __future__ import annotations

import hashlib
import io
import json
import threading
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import ClassVar

import pytest
from crypto_sensor_fabric.storage import (
    ComponentTooLong,
    CrossFilesystemAtomicityError,
    IntegrityState,
    LocalBlobStore,
    PutDisposition,
    StorageEncoding,
)
from crypto_sensor_fabric.storage.atomic import (
    OP_ATOMIC_PUBLISH,
    OP_EXISTING_FINAL_VERIFY,
    OP_FILE_FLUSH,
    OP_FILE_FSYNC,
    OP_PARENT_DIR_FSYNC,
    OP_STAGE_VERIFY,
    OP_STAGE_WRITE,
    OP_STAGING_CLEANUP,
    OP_SUCCESS_RETURN,
    FaultError,
    FaultPoint,
    ListOpRecorder,
    RaiseFaultHook,
    is_canonical_durable_order,
    is_canonical_reuse_order,
)

FIXED = datetime(2026, 9, 4, 12, 0, 0, tzinfo=UTC)

MEDIA = "application/octet-stream"

# Generated I03 evidence artifacts (I03 §74/§75).  Written deterministically
# by tests — never hand-declared — into the frozen evidence directory.
EVIDENCE_DIR = (
    Path(__file__).resolve().parents[3]
    / "research"
    / "crypto_foundry"
    / "sensor_fabric"
    / "evidence"
    / "bloc_04"
)


def deterministic_bytes(size: int, seed: int = 12345) -> bytes:
    out = bytearray()
    state = seed
    while len(out) < size:
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        out.append(state & 0xFF)
    return bytes(out)


def make_store(tmp_path: Path, **kwargs: object) -> LocalBlobStore:
    return LocalBlobStore(tmp_path, clock=lambda: FIXED, **kwargs)


def final_path_for(tmp_path: Path, sha: str, encoding: StorageEncoding) -> Path:
    suffix = ".blob" if encoding is StorageEncoding.NONE else ".blob.zst"
    return (
        tmp_path / "blobs" / "sha256" / sha[:2] / sha[2:4] / f"{sha}{suffix}"
    )


class TestStagingIsolation:
    @pytest.mark.parametrize(
        "point",
        [
            FaultPoint.STAGE_WRITE,
            FaultPoint.BEFORE_FILE_FSYNC,
            FaultPoint.BEFORE_STAGE_VERIFY,
            FaultPoint.BEFORE_PUBLISH,
        ],
    )
    def test_partial_stage_never_exposes_final(self, tmp_path, point: FaultPoint) -> None:
        data = b"crash during staging"
        store = make_store(tmp_path)
        sha = hashlib.sha256(data).hexdigest()
        hooks = RaiseFaultHook(point)
        with pytest.raises(FaultError):
            store.put(
                io.BytesIO(data),
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
                fault_hooks=hooks,
            )
        assert not final_path_for(tmp_path, sha, StorageEncoding.NONE).exists()
        assert list((tmp_path / "staging").rglob("*.partial")), "partial staging may exist"

    def test_adversarial_reader_never_observes_partial_final(self, tmp_path) -> None:
        data = deterministic_bytes(2_000_000, seed=99)
        sha = hashlib.sha256(data).hexdigest()
        final = final_path_for(tmp_path, sha, StorageEncoding.NONE)
        store = make_store(tmp_path, chunk_size=1 << 14)
        errors: list[str] = []

        def writer() -> None:
            try:
                store.put(
                    io.BytesIO(data),
                    storage_encoding=StorageEncoding.NONE,
                    source_media_type=MEDIA,
                )
            except Exception as exc:  # noqa: BLE001 - test harness only
                errors.append(repr(exc))

        thread = threading.Thread(target=writer)
        thread.start()
        observed = 0
        while thread.is_alive() or observed == 0:
            if final.exists():
                observed += 1
                with open(final, "rb") as fh:
                    got = fh.read()
                assert got == data, "reader observed a partial final object!"
            time.sleep(0.001)
        thread.join()
        assert not errors
        assert observed >= 1


class TestCrashMatrix:
    """I03 §74: deterministic fault injection, one row per crash point."""

    EXPECTED_STATES: ClassVar[dict[FaultPoint, str]] = {
        FaultPoint.STAGE_WRITE: "UNCOMMITTED_STAGING",
        FaultPoint.BEFORE_FILE_FSYNC: "UNCOMMITTED_STAGING",
        FaultPoint.BEFORE_STAGE_VERIFY: "UNCOMMITTED_STAGING",
        FaultPoint.BEFORE_PUBLISH: "UNCOMMITTED_STAGING",
        FaultPoint.AFTER_PUBLISH_BEFORE_DIR_FSYNC: "ORPHAN_DURABLE_BLOB",
        FaultPoint.AFTER_DIR_FSYNC_BEFORE_RETURN: "DURABLE_COMMITTED",
    }

    @pytest.mark.parametrize("point", list(EXPECTED_STATES))
    def test_crash_row(self, tmp_path, point: FaultPoint) -> None:
        data = f"crash-{point.value}".encode()
        store = make_store(tmp_path)
        sha = hashlib.sha256(data).hexdigest()
        hooks = RaiseFaultHook(point)
        ops = ListOpRecorder()
        try:
            store.put(
                io.BytesIO(data),
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
                fault_hooks=hooks,
                ops=ops,
            )
            raised = False
        except FaultError:
            raised = True
        assert raised

        final_exists = final_path_for(tmp_path, sha, StorageEncoding.NONE).exists()
        staging_exists = bool(list((tmp_path / "staging").rglob("*.partial")))
        success_returned = OP_SUCCESS_RETURN in ops.ops
        state = self.EXPECTED_STATES[point]

        if state == "UNCOMMITTED_STAGING":
            assert final_exists is False
            assert success_returned is False
        elif state == "ORPHAN_DURABLE_BLOB":
            assert final_exists is True
            assert success_returned is False
            assert OP_PARENT_DIR_FSYNC not in ops.ops
        elif state == "DURABLE_COMMITTED":
            assert final_exists is True
            assert success_returned is False  # crash before return, but durable
            assert OP_PARENT_DIR_FSYNC in ops.ops
            check = store.verify_blob(sha, StorageEncoding.NONE)
            assert check.integrity_state is IntegrityState.LOCAL_HASH_VERIFIED
        assert staging_exists is True

    def test_crash_matrix_artifact_written(self, tmp_path) -> None:
        """Regenerate BLOC_04_I03_CRASH_MATRIX.json deterministically (I03 §74)."""
        rows: list[dict[str, object]] = []
        for point, expected_state in self.EXPECTED_STATES.items():
            data = f"crash-matrix-{point.value}".encode()
            store = make_store(tmp_path)
            sha = hashlib.sha256(data).hexdigest()
            ops = ListOpRecorder()
            with pytest.raises(FaultError):
                store.put(
                    io.BytesIO(data),
                    storage_encoding=StorageEncoding.NONE,
                    source_media_type=MEDIA,
                    fault_hooks=RaiseFaultHook(point),
                    ops=ops,
                )
            rows.append(
                {
                    "fault_point": point.value,
                    "final_exists": final_path_for(
                        tmp_path, sha, StorageEncoding.NONE
                    ).exists(),
                    "staging_exists": bool(
                        list((tmp_path / "staging").rglob("*.partial"))
                    ),
                    "success_returned": OP_SUCCESS_RETURN in ops.ops,
                    "expected_state": expected_state,
                    "test_name": f"test_crash_row[{point.value}]",
                }
            )
            # row-local staging state: clear this row's leftover before the next
            for leftover in (tmp_path / "staging").rglob("*.partial"):
                leftover.unlink()
        out_path = EVIDENCE_DIR / "BLOC_04_I03_CRASH_MATRIX.json"
        out_path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
        assert len(rows) == 6
        assert all(row["success_returned"] is False for row in rows)

    def test_retry_after_durable_publication_dedupes(self, tmp_path) -> None:
        data = b"retry after crash F"
        store = make_store(tmp_path)
        hooks = RaiseFaultHook(FaultPoint.AFTER_DIR_FSYNC_BEFORE_RETURN)
        with pytest.raises(FaultError):
            store.put(
                io.BytesIO(data),
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
                fault_hooks=hooks,
            )
        result = store.put_bytes(data, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA)
        assert result.disposition is PutDisposition.REUSED_EXISTING


class TestOperationOrder:
    def test_successful_put_full_canonical_order(self, tmp_path) -> None:
        store = make_store(tmp_path)
        ops = ListOpRecorder()
        store.put_bytes(b"order proof", storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA, ops=ops)
        assert ops.ops[0] == OP_STAGE_WRITE
        assert ops.ops[1] == OP_FILE_FLUSH
        assert ops.ops[2] == OP_FILE_FSYNC
        assert ops.ops[3] == OP_STAGE_VERIFY
        assert ops.ops.index(OP_ATOMIC_PUBLISH) < ops.ops.index(OP_PARENT_DIR_FSYNC)
        assert ops.ops.index(OP_PARENT_DIR_FSYNC) < ops.ops.index(OP_SUCCESS_RETURN)
        assert ops.ops[-1] == OP_SUCCESS_RETURN
        assert ops.ops[-2] == OP_STAGING_CLEANUP
        assert ops.ops[-3] == OP_PARENT_DIR_FSYNC
        assert ops.ops[-4] == OP_ATOMIC_PUBLISH
        assert is_canonical_durable_order(ops.ops)

    def test_atomic_order_artifact_written(self, tmp_path) -> None:
        """Regenerate BLOC_04_I03_ATOMIC_ORDER.json deterministically (I03 §75)."""
        store = make_store(tmp_path)
        ops = ListOpRecorder()
        store.put_bytes(
            b"deterministic atomic order evidence",
            storage_encoding=StorageEncoding.NONE,
            source_media_type=MEDIA,
            ops=ops,
        )
        payload: dict[str, object] = {
            "operation_order": list(ops.ops),
            "canonical_order_contract": [
                OP_STAGE_WRITE,
                OP_FILE_FLUSH,
                OP_FILE_FSYNC,
                OP_STAGE_VERIFY,
                OP_ATOMIC_PUBLISH,
                OP_PARENT_DIR_FSYNC,
                OP_SUCCESS_RETURN,
            ],
            "order_proven": is_canonical_durable_order(ops.ops),
            "success_returned_last": ops.ops[-1] == OP_SUCCESS_RETURN,
            "parent_fsync_before_success": (
                ops.ops.index(OP_PARENT_DIR_FSYNC)
                < ops.ops.index(OP_SUCCESS_RETURN)
            ),
            "encoding": "NONE",
        }
        out_path = EVIDENCE_DIR / "BLOC_04_I03_ATOMIC_ORDER.json"
        out_path.write_text(
            json.dumps(payload, indent=2) + "\n", encoding="utf-8"
        )
        assert payload["order_proven"] is True
        assert payload["success_returned_last"] is True

    def test_success_never_before_parent_fsync(self, tmp_path) -> None:
        for i, point in enumerate(
            (
                FaultPoint.AFTER_PUBLISH_BEFORE_DIR_FSYNC,
                FaultPoint.AFTER_DIR_FSYNC_BEFORE_RETURN,
            )
        ):
            store = make_store(tmp_path)
            ops = ListOpRecorder()
            with pytest.raises(FaultError):
                store.put_bytes(
                    f"x-{i}".encode(),
                    storage_encoding=StorageEncoding.NONE,
                    source_media_type=MEDIA,
                    fault_hooks=RaiseFaultHook(point),
                    ops=ops,
                )
            assert OP_SUCCESS_RETURN not in ops.ops
            if OP_PARENT_DIR_FSYNC in ops.ops:
                assert ops.ops.index(OP_ATOMIC_PUBLISH) < ops.ops.index(
                    OP_PARENT_DIR_FSYNC
                )
            else:
                assert OP_ATOMIC_PUBLISH in ops.ops


class TestConcurrency:
    def test_concurrent_identical_writers_one_final(self, tmp_path) -> None:
        data = deterministic_bytes(400_000, seed=20260904)
        store = make_store(tmp_path, chunk_size=1 << 16)
        count = 8
        results: list[str] = []
        lock = threading.Lock()
        barrier = threading.Barrier(count)

        def worker() -> None:
            barrier.wait()
            result = store.put(
                io.BytesIO(data),
                storage_encoding=StorageEncoding.ZSTD,
                source_media_type=MEDIA,
            )
            with lock:
                results.append(result.disposition.value)

        threads = [threading.Thread(target=worker) for _ in range(count)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        assert results.count(PutDisposition.COMMITTED_NEW.value) == 1
        assert results.count(PutDisposition.REUSED_EXISTING.value) == count - 1
        sha = hashlib.sha256(data).hexdigest()
        finals = list((tmp_path / "blobs" / "sha256" / sha[:2] / sha[2:4]).glob("*.blob.zst"))
        assert len(finals) == 1
        check = store.verify_blob(sha, StorageEncoding.ZSTD, expected_byte_length=len(data))
        assert check.integrity_state is IntegrityState.LOCAL_HASH_VERIFIED

    def test_concurrent_distinct_writers_no_crosstalk(self, tmp_path) -> None:
        store = make_store(tmp_path)
        payloads = [deterministic_bytes(50_000, seed=i) for i in range(6)]
        results: list[str] = []
        lock = threading.Lock()
        barrier = threading.Barrier(len(payloads))

        def worker(data: bytes) -> None:
            barrier.wait()
            result = store.put(
                io.BytesIO(data),
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
            )
            with lock:
                results.append(result.blob.blob_sha256)

        threads = [threading.Thread(target=worker, args=(p,)) for p in payloads]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        assert sorted(results) == sorted(hashlib.sha256(p).hexdigest() for p in payloads)
        for p in payloads:
            sha = hashlib.sha256(p).hexdigest()
            with store.open_blob(sha, StorageEncoding.NONE) as fh:
                assert fh.read() == p


class TestCrossFilesystem:
    def test_cross_device_commit_denied(self, tmp_path) -> None:
        data = b"deny cross-device atomicity"
        staging_dir = tmp_path / "staging"

        def probe(path: Path) -> int:
            if path == staging_dir or staging_dir in path.parents:
                return 1
            return 2

        store = LocalBlobStore(tmp_path, clock=lambda: FIXED, device_probe=probe)
        sha = hashlib.sha256(data).hexdigest()
        with pytest.raises(CrossFilesystemAtomicityError):
            store.put(
                io.BytesIO(data),
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
            )
        assert not final_path_for(tmp_path, sha, StorageEncoding.NONE).exists()
        assert list((tmp_path / "staging").rglob("*.partial")), "staging preserved"

    def test_same_device_default_probe_accepted(self, tmp_path) -> None:
        store = make_store(tmp_path)
        result = store.put_bytes(b"same disk", storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA)
        assert result.disposition is PutDisposition.COMMITTED_NEW


class TestReuseDurability:
    """SENSOR-B4-I03R1 Defect A: verified bytes are not durable bytes.

    Every REUSED_EXISTING path must prove CURRENT parent-directory durability
    BEFORE success: ordinary dedupe, publish-race loser, retry after crash E
    (ORPHAN_DURABLE_BLOB) and retry after crash F.
    """

    def test_retry_after_crash_E_proves_parent_fsync_before_success(
        self, tmp_path
    ) -> None:
        """Crash-E orphan must NOT be silently promoted by a plain retry."""
        data = b"orphan retry must re-establish durability"
        store = make_store(tmp_path)
        sha = hashlib.sha256(data).hexdigest()
        with pytest.raises(FaultError):
            store.put_bytes(
                data,
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
                fault_hooks=RaiseFaultHook(
                    FaultPoint.AFTER_PUBLISH_BEFORE_DIR_FSYNC
                ),
            )
        # Frozen crash-E truth: final exists, NO durable success returned,
        # parent fsync never observed.  The crashed attempt's staging is
        # preserved crash evidence (I03 §42 — no auto-recovery scanner here).
        assert final_path_for(tmp_path, sha, StorageEncoding.NONE).exists()
        crash_staging = list((tmp_path / "staging").rglob("*.partial"))
        assert len(crash_staging) == 1
        # I03R1 §6: explicit retry with observation of the durability step.
        ops = ListOpRecorder()
        result = store.put_bytes(
            data,
            storage_encoding=StorageEncoding.NONE,
            source_media_type=MEDIA,
            ops=ops,
        )
        assert result.disposition is PutDisposition.REUSED_EXISTING
        # Durability re-established BEFORE success, no byte rewritten.
        assert OP_EXISTING_FINAL_VERIFY in ops.ops
        assert OP_PARENT_DIR_FSYNC in ops.ops
        assert ops.ops.index(OP_PARENT_DIR_FSYNC) < ops.ops.index(
            OP_SUCCESS_RETURN
        )
        assert is_canonical_reuse_order(ops.ops)
        check = store.verify_blob(sha, StorageEncoding.NONE)
        assert check.integrity_state is IntegrityState.LOCAL_HASH_VERIFIED
        # The retry cleaned its OWN staging; the crash-E evidence file remains
        # untouched for the later recovery checkpoint (I03 §42/§26, no I08).
        after = list((tmp_path / "staging").rglob("*.partial"))
        assert [p.name for p in after] == [p.name for p in crash_staging]

    def test_retry_after_crash_E_idempotent_identity(self, tmp_path) -> None:
        data = b"identity survives orphan retry"
        store = make_store(tmp_path)
        sha = hashlib.sha256(data).hexdigest()
        with pytest.raises(FaultError):
            store.put_bytes(
                data,
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
                fault_hooks=RaiseFaultHook(
                    FaultPoint.AFTER_PUBLISH_BEFORE_DIR_FSYNC
                ),
            )
        final = final_path_for(tmp_path, sha, StorageEncoding.NONE)
        before = final.read_bytes()
        result = store.put_bytes(
            data, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA
        )
        assert result.disposition is PutDisposition.REUSED_EXISTING
        assert result.blob.blob_sha256 == sha
        # Content identity unchanged, final bytes never rewritten.
        assert final.read_bytes() == before

    def test_ordinary_reuse_performs_final_parent_fsync(self, tmp_path) -> None:
        data = b"ordinary dedupe also proves durability"
        store = make_store(tmp_path)
        store.put_bytes(
            data, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA
        )
        ops = ListOpRecorder()
        result = store.put_bytes(
            data,
            storage_encoding=StorageEncoding.NONE,
            source_media_type=MEDIA,
            ops=ops,
        )
        assert result.disposition is PutDisposition.REUSED_EXISTING
        assert OP_EXISTING_FINAL_VERIFY in ops.ops
        assert ops.ops.index(OP_PARENT_DIR_FSYNC) < ops.ops.index(
            OP_SUCCESS_RETURN
        )
        assert is_canonical_reuse_order(ops.ops)

    def test_publish_race_loser_proves_parent_fsync_before_success(
        self, tmp_path
    ) -> None:
        """Race loser verifies winner THEN fsyncs final parent (I03R1 §8)."""
        data = b"race loser durability parity"
        store = make_store(tmp_path)
        first = store.put_bytes(
            data, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA
        )
        assert first.disposition is PutDisposition.COMMITTED_NEW
        # Simulate the loser: it published second, hit TargetExists, verified
        # the winner, and must now fsync the winner's parent before success.
        ops = ListOpRecorder()
        second = store.put_bytes(
            data,
            storage_encoding=StorageEncoding.NONE,
            source_media_type=MEDIA,
            ops=ops,
        )
        assert second.disposition is PutDisposition.REUSED_EXISTING
        assert is_canonical_reuse_order(ops.ops)
        assert ops.ops.index(OP_PARENT_DIR_FSYNC) < ops.ops.index(
            OP_SUCCESS_RETURN
        )

    def test_reuse_never_overwrites_final_bytes(self, tmp_path) -> None:
        data = b"immutable across durability re-establishment"
        store = make_store(tmp_path)
        store.put_bytes(
            data, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA
        )
        sha = hashlib.sha256(data).hexdigest()
        final = final_path_for(tmp_path, sha, StorageEncoding.NONE)
        before = final.read_bytes()
        store.put_bytes(
            data, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA
        )
        assert final.read_bytes() == before


class TestLongComponent:
    def test_ordinary_key_components_accepted(self, tmp_path) -> None:
        store = make_store(tmp_path)
        result = store.put_bytes(b"x", storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA)
        assert result.disposition is PutDisposition.COMMITTED_NEW

    def test_over_limit_component_rejected_before_final_write(self, tmp_path) -> None:
        def tiny_name_max(path: Path) -> int:
            return 8

        store = make_store(tmp_path, name_max_probe=tiny_name_max)
        # The 68-char '<sha>.blob' component exceeds the injected 8-byte
        # limit; the failure must happen BEFORE any final artifact write.
        with pytest.raises(ComponentTooLong):
            store.put_bytes(b"x" * 100, storage_encoding=StorageEncoding.NONE, source_media_type=MEDIA)
        # The failure happens BEFORE any final artifact write: the final
        # fanout namespace is never even created.
        assert not (tmp_path / "blobs").exists()

    def test_over_limit_job_id_rejected_before_staging_artifact(self, tmp_path) -> None:
        """An over-limit caller-supplied job_id fails typed, BEFORE any write (I03 §10/§13/§45)."""
        store = make_store(tmp_path)
        with pytest.raises(ComponentTooLong):
            store.put_bytes(
                b"x",
                storage_encoding=StorageEncoding.NONE,
                source_media_type=MEDIA,
                job_id="j" * 300,
            )
        assert not (tmp_path / "staging").exists()
        assert not (tmp_path / "blobs").exists()

    def test_no_truncation_or_normalization(self, tmp_path) -> None:
        # Canonical escaped identity that exceeds the limit fails EXPLICITLY.
        long_native = "instrument_" + "x" * 400 + "/with/slashes"
        from crypto_sensor_fabric.storage.paths import escape_path_segment

        encoded = escape_path_segment(long_native)
        assert len(encoded.encode("utf-8")) > 255
        from crypto_sensor_fabric.storage.atomic import validate_component_length

        with pytest.raises(ComponentTooLong):
            validate_component_length(encoded, 255)
