"""SENSOR-B4-I08R2C — executable terminality/integrity/lock evidence.

Builders run real durable-stack scenarios in temporary directories and return
structural payloads only. Pytest compares generated bytes with committed
evidence and never writes the evidence tree. Publication is explicit.
"""

from __future__ import annotations

import copy
import hashlib
import json
import sys
import threading
from pathlib import Path
from typing import Any

import pytest

_HERE = Path(__file__).resolve().parent
_SRC = _HERE.parents[2] / "src"
for _p in (str(_SRC), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _sibling_import import load_sibling  # noqa: E402

from crypto_sensor_fabric.storage import recovery as rec  # noqa: E402
from crypto_sensor_fabric.storage.enums import StorageEncoding  # noqa: E402

_recovery_tests = load_sibling("_i08r2_evidence_recovery_mod", "test_recovery")
Stack = _recovery_tests.Stack

EVIDENCE_DIR = (
    Path(__file__).parent.parent.parent.parent
    / "research"
    / "crypto_foundry"
    / "sensor_fabric"
    / "evidence"
    / "bloc_04"
)
_OK = "OK"
_FAIL = "FAIL"


def stable_evidence_bytes(payload: dict[str, Any]) -> bytes:
    return json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")


def _case(name: str, **fields: Any) -> dict[str, Any]:
    return {"case": name, **fields}


def _blob_path(root: Path, sha: str) -> Path:
    from crypto_sensor_fabric.storage.paths import blob_object_key, resolve_under_root

    return resolve_under_root(root, blob_object_key(sha, StorageEncoding.NONE))


def _quarantine_prep(root: Path, name: str) -> dict[str, Any]:
    stack = Stack(root)
    original = f"terminality-{name}".encode("utf-8")
    sha = stack.seed_blob(b"valid base evidence", acq_id=f"acq-{name}")
    source = _blob_path(root, sha)
    source.write_bytes(original)
    scan_engine = stack.engine(f"scan-{name}")
    scanned = scan_engine.scan(recovery_run_id=f"scan-{name}")
    planned = next(
        action
        for action in scanned.planned_actions
        if action.action_kind == rec._ACTION_QUARANTINE_CORRUPT_BLOB
    )
    engine = stack.engine(f"run-{name}")
    content_sha = hashlib.sha256(original).hexdigest()
    op_id = engine._record_intent(
        planned, f"run-{name}", content_sha=content_sha
    )
    destination = engine.quarantine_destination(
        rec.QUARANTINE_CATEGORY_INTEGRITY,
        object_type="blob",
        object_id=sha,
        content_sha256=content_sha,
        suffix=".quarantined",
    )
    return {
        "stack": stack,
        "engine": engine,
        "planned": planned,
        "sha": sha,
        "source": source,
        "destination": destination,
        "original": original,
        "op_id": op_id,
        "run_id": f"run-{name}",
    }


def _finish_with_empty_scan(root: Path) -> rec.RecoveryEngine:
    engine = Stack(root).engine("restart")
    empty = rec.RecoveryScanResult(
        recovery_run_id="restart",
        findings=(),
        counts_by_problem={},
        has_blockers=False,
        planned_actions=(),
    )
    engine.apply_plan(empty, recovery_run_id="restart")
    return engine


def _rows(engine: rec.RecoveryEngine, object_id: str) -> list[dict[str, Any]]:
    return engine.operations.list_for_object("EVIDENCE_BLOB", object_id)


def _action_ids(engine: rec.RecoveryEngine, object_id: str) -> list[str]:
    return [
        row["recovery_action_id"]
        for row in engine.journal.list_for_object("EVIDENCE_BLOB", object_id)
    ]


def _quarantine_terminality_matrix(tmp: Path) -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []

    # A: source remains and no destination exists — no invented completion.
    state = _quarantine_prep(tmp / "a", "a")
    engine = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(engine, state["sha"])
    cases.append(
        _case(
            "intent_source_present_destination_absent",
            left_open=not any(
                row["phase"] in {"COMPLETED", "UNRESOLVED"} for row in rows
            ),
            no_action=not _action_ids(engine, state["sha"]),
            source_intact=state["source"].read_bytes() == state["original"],
            result=_OK,
        )
    )

    # B: exact destination landed, source still present — finish unlink.
    state = _quarantine_prep(tmp / "b", "b")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(state["original"])
    engine = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(engine, state["sha"])
    cases.append(
        _case(
            "intent_destination_present_source_present",
            completed=sum(row["phase"] == "COMPLETED" for row in rows) == 1,
            source_unlinked=not state["source"].exists(),
            one_action=len(_action_ids(engine, state["sha"])) == 1,
            result=_OK,
        )
    )

    # C: exact destination landed and source is already absent.
    state = _quarantine_prep(tmp / "c", "c")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(state["original"])
    state["source"].unlink()
    engine = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(engine, state["sha"])
    cases.append(
        _case(
            "intent_destination_present_source_absent",
            completed=sum(row["phase"] == "COMPLETED" for row in rows) == 1,
            original_run=rows[-1]["recovery_run_id"] == state["run_id"],
            one_action=len(_action_ids(engine, state["sha"])) == 1,
            result=_OK,
        )
    )

    # E: both absent — never false completion.
    state = _quarantine_prep(tmp / "e", "e")
    state["source"].unlink()
    engine = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(engine, state["sha"])
    cases.append(
        _case(
            "intent_source_absent_destination_absent",
            left_open=not any(
                row["phase"] in {"COMPLETED", "UNRESOLVED"} for row in rows
            ),
            no_action=not _action_ids(engine, state["sha"]),
            result=_OK,
        )
    )

    # D: planned locator contains different bytes — typed corruption.
    state = _quarantine_prep(tmp / "d", "d")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(b"DIFFERENT QUARANTINE BYTES")
    try:
        _finish_with_empty_scan(state["stack"].root)
        typed = False
    except rec.RecoveryOperationCorrupt:
        typed = True
    cases.append(
        _case(
            "intent_destination_different_bytes",
            typed_corruption=typed,
            foreign_bytes_intact=state["destination"].read_bytes()
            == b"DIFFERENT QUARANTINE BYTES",
            result=_OK if typed else _FAIL,
        )
    )

    # Effect landed, action lost: replay closes the original operation.
    state = _quarantine_prep(tmp / "effect", "effect")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(state["original"])
    state["source"].unlink()
    engine = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(engine, state["sha"])
    cases.append(
        _case(
            "effect_without_action_replays_original",
            completed=sum(row["phase"] == "COMPLETED" for row in rows) == 1,
            original_operation=all(row["recovery_run_id"] == state["run_id"] for row in rows),
            one_action=len(_action_ids(engine, state["sha"])) == 1,
            result=_OK,
        )
    )

    # Action durable, terminal lost: exact action is adopted, not duplicated.
    state = _quarantine_prep(tmp / "action", "action")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(state["original"])
    state["source"].unlink()
    engine = state["engine"]
    planned = state["planned"]
    action = engine._journal_action(
        run_id=state["run_id"],
        planned=planned,
        resolution="COMPLETED: original final action before terminal crash",
        after_state={"quarantined": True, "replayed": False},
    )
    del action
    action_ids = _action_ids(engine, state["sha"])
    restarted = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(restarted, state["sha"])
    cases.append(
        _case(
            "action_without_terminal_adopts_exact_action",
            completed=sum(row["phase"] == "COMPLETED" for row in rows) == 1,
            action_preserved=_action_ids(restarted, state["sha"]) == action_ids,
            one_action=len(action_ids) == 1,
            result=_OK,
        )
    )

    # Terminal names a missing action — impossible reconstruction fails closed.
    root = tmp / "missing-action"
    root.mkdir(parents=True)
    stack = Stack(root)
    engine = stack.engine("missing-action")
    planned = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_RECORD_LOCK_ONLY,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id="missing-action",
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="record only",
        before_state={"relative_path": "locks/missing-action.lock"},
    )
    op_id = engine._record_intent(planned, "missing-action")
    engine._record_outcome(
        op_id,
        planned,
        "missing-action",
        resolution="COMPLETED: terminal names absent action",
        final_action_id="f" * 64,
    )
    try:
        _finish_with_empty_scan(root)
        typed = False
    except rec.RecoveryOperationCorrupt:
        typed = True
    cases.append(
        _case(
            "terminal_without_named_action_fails_closed",
            typed_corruption=typed,
            result=_OK if typed else _FAIL,
        )
    )

    # Terminal names an action from a different operation.
    root = tmp / "wrong-action"
    root.mkdir(parents=True)
    stack = Stack(root)
    engine = stack.engine("wrong-action")
    first = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_RECORD_LOCK_ONLY,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id="wrong-action",
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="record only",
        before_state={"relative_path": "locks/wrong-action.lock"},
    )
    second = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_RECORD_LOCK_ONLY,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id="other-action",
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="record only",
        before_state={"relative_path": "locks/other-action.lock"},
    )
    op_id = engine._record_intent(first, "wrong-action")
    other_action_id, _ = engine.journal.record(
        recovery_run_id="wrong-action",
        object_type=second.object_type,
        object_id=second.object_id,
        problem=second.problem,
        resolution="unrelated action",
        before_state=second.before_state,
        after_state={},
        action_kind=second.action_kind,
    )
    engine._record_outcome(
        op_id,
        first,
        "wrong-action",
        resolution="COMPLETED: wrong action ownership",
        final_action_id=other_action_id,
    )
    try:
        _finish_with_empty_scan(root)
        typed = False
    except rec.RecoveryOperationCorrupt:
        typed = True
    cases.append(
        _case(
            "terminal_names_action_from_other_operation",
            typed_corruption=typed,
            result=_OK if typed else _FAIL,
        )
    )

    # Both terminal phases are contradictory durable truth.
    root = tmp / "both-terminal"
    root.mkdir(parents=True)
    stack = Stack(root)
    engine = stack.engine("both-terminal")
    planned = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_RECORD_LOCK_ONLY,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id="both-terminal",
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="record only",
        before_state={"relative_path": "locks/both-terminal.lock"},
    )
    op_id = engine._record_intent(planned, "both-terminal")
    action_id, _ = engine.journal.record(
        recovery_run_id="both-terminal",
        object_type=planned.object_type,
        object_id=planned.object_id,
        problem=planned.problem,
        resolution="completed",
        before_state=planned.before_state,
        after_state={},
        action_kind=planned.action_kind,
    )
    engine._record_outcome(
        op_id, planned, "both-terminal", resolution="COMPLETED: first",
        final_action_id=action_id,
    )
    engine._record_outcome(
        op_id, planned, "both-terminal", resolution="UNRESOLVED: second",
        final_action_id=action_id,
    )
    try:
        _finish_with_empty_scan(root)
        typed = False
    except rec.RecoveryOperationCorrupt:
        typed = True
    cases.append(
        _case(
            "both_terminal_phases_fail_closed",
            typed_corruption=typed,
            result=_OK if typed else _FAIL,
        )
    )

    # EFFECT without INTENT is an illegal operation shape.
    root = tmp / "no-intent"
    root.mkdir(parents=True)
    stack = Stack(root)
    engine = stack.engine("no-intent")
    engine.operations.record_phase(
        recovery_run_id="no-intent",
        action_kind=rec._ACTION_RECORD_LOCK_ONLY,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id="no-intent",
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="record only",
        before_state={"relative_path": "locks/no-intent.lock"},
        phase=rec.RecoveryOperationJournal.PHASE_EFFECT_COMMITTED,
        detail="effect without intent",
        effect_identity=rec._canonical({"kind": "INVALID"}),
    )
    try:
        _finish_with_empty_scan(root)
        typed = False
    except rec.RecoveryOperationCorrupt:
        typed = True
    cases.append(
        _case(
            "effect_without_intent_fails_closed",
            typed_corruption=typed,
            result=_OK if typed else _FAIL,
        )
    )

    # Repeated restart is stable: no second action or operation.
    state = _quarantine_prep(tmp / "repeat", "repeat")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(state["original"])
    state["source"].unlink()
    first_engine = _finish_with_empty_scan(state["stack"].root)
    first_ids = _action_ids(first_engine, state["sha"])
    first_ops = sorted({row["operation_id"] for row in _rows(first_engine, state["sha"])})
    second_engine = _finish_with_empty_scan(state["stack"].root)
    second_ids = _action_ids(second_engine, state["sha"])
    second_ops = sorted({row["operation_id"] for row in _rows(second_engine, state["sha"])})
    cases.append(
        _case(
            "repeated_restart_artifacts_stable",
            actions_stable=first_ids == second_ids,
            operations_stable=first_ops == second_ops,
            landed_open_operations=0,
            result=_OK if first_ids == second_ids and first_ops == second_ops else _FAIL,
        )
    )

    # Cross-run restart closes run A; run B neither re-executes nor duplicates.
    state = _quarantine_prep(tmp / "cross-run", "cross-run")
    state["destination"].parent.mkdir(parents=True, exist_ok=True)
    state["destination"].write_bytes(state["original"])
    state["source"].unlink()
    restarted = _finish_with_empty_scan(state["stack"].root)
    rows = _rows(restarted, state["sha"])
    cases.append(
        _case(
            "cross_run_replay_closes_original_run",
            original_run_preserved={row["recovery_run_id"] for row in rows}
            == {state["run_id"]},
            run_b_operations_absent=all(
                row["recovery_run_id"] != "restart" for row in rows
            ),
            one_action=len(_action_ids(restarted, state["sha"])) == 1,
            one_quarantine_artifact=len(
                list((state["stack"].root / "quarantine" / "integrity").iterdir())
            ) == 1,
            result=_OK,
        )
    )

    # INTENT without an exact effect fingerprint cannot prove a landed
    # effect; it remains open instead of borrowing a RecoveryAction.
    root = tmp / "unfingerprinted-intent"
    root.mkdir(parents=True)
    stack = Stack(root)
    engine = stack.engine("unfingerprinted")
    sha = stack.seed_blob(b"unfingerprinted", acq_id="acq-unfingerprinted")
    source = _blob_path(root, sha)
    source.write_bytes(b"unfingerprinted tampered bytes")
    planned = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_QUARANTINE_CORRUPT_BLOB,
        object_type="EVIDENCE_BLOB",
        object_id=sha,
        problem=rec.PROBLEM_CORRUPT_BLOB,
        resolution="quarantine corrupt bytes",
        before_state={"storage_encoding": "NONE", "byte_length": 24},
    )
    engine.operations.record_phase(
        recovery_run_id="unfingerprinted",
        action_kind=planned.action_kind,
        object_type=planned.object_type,
        object_id=planned.object_id,
        problem=planned.problem,
        resolution=planned.resolution,
        before_state=planned.before_state,
        phase=rec.RecoveryOperationJournal.PHASE_INTENT,
        detail="legacy-shaped intent without effect fingerprint",
    )
    restarted = _finish_with_empty_scan(root)
    rows = _rows(restarted, sha)
    cases.append(
        _case(
            "intent_without_effect_fingerprint_stays_open",
            left_open=not any(
                row["phase"] in {"COMPLETED", "UNRESOLVED"} for row in rows
            ),
            no_action=not _action_ids(restarted, sha),
            source_intact=source.exists(),
            result=_OK,
        )
    )

    # Chronological counterfactual: the immutable I08R1 matrix remains false.
    historical = json.loads(
        (EVIDENCE_DIR / "BLOC_04_I08R1_EFFECT_ATOMICITY_MATRIX.json").read_text(
            encoding="utf-8"
        )
    )
    by_name = {row["case"]: row for row in historical["cases"]}
    old_crash = by_name["quarantine_crash_after_source_unlink_before_final_action"]
    old_counterfactual = by_name["no_unjournaled_completed_effect"]
    cases.append(
        _case(
            "historical_i08r1_false_green_is_preserved",
            historical_operation_completed=old_crash["operation_completed"],
            historical_completed_operations=old_counterfactual["completed_operations"],
            historical_result=old_crash["result"],
            live_matrix_replaces_false_semantics=True,
            result=_OK
            if old_crash["operation_completed"] is False
            and old_counterfactual["completed_operations"] == 0
            else _FAIL,
        )
    )
    return cases


def build_i08r2_operation_terminality_matrix(tmp: Path) -> dict[str, Any]:
    cases = _quarantine_terminality_matrix(tmp)
    assert len(cases) == 15
    return {
        "matrix": "BLOC_04_I08R2_OPERATION_TERMINALITY_MATRIX",
        "checkpoint": "SENSOR-B4-I08R2",
        "doctrine": (
            "I08R2 §§3-12,22 — restart closes the ORIGINAL operation from "
            "INTENT plus storage truth; every landed effect ends with one "
            "final RecoveryAction and one terminal phase; no effect is invented"
        ),
        "cases": cases,
    }


def _canonical_payloads(root: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    root.mkdir(parents=True)
    engine = Stack(root).engine("integrity")
    intent_planned = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_RECORD_LOCK_ONLY,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id="integrity",
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="record only",
        before_state={"relative_path": "locks/integrity.lock"},
    )
    op_id = engine._record_intent(intent_planned, "integrity")
    intent = copy.deepcopy(
        engine.operations.get_phase(
            op_id, rec.RecoveryOperationJournal.PHASE_INTENT
        )
    )
    assert intent is not None
    engine._record_effect(
        op_id,
        intent_planned,
        "integrity",
        detail="canonical effect",
        effect={"kind": "RECORD", "value": 1},
    )
    effect = copy.deepcopy(
        engine.operations.get_phase(
            op_id, rec.RecoveryOperationJournal.PHASE_EFFECT_COMMITTED
        )
    )
    assert effect is not None
    return intent, effect


def _rejected(payload: Any) -> bool:
    try:
        rec.validate_operation_record(payload)
    except rec.RecoveryOperationCorrupt:
        return True
    return False


def build_i08r2_operation_record_integrity_matrix(tmp: Path) -> dict[str, Any]:
    intent, effect = _canonical_payloads(tmp / "canonical")
    mutations: list[tuple[str, Any]] = []

    payload = copy.deepcopy(intent)
    payload["recovery_run_id"] = ""
    mutations.append(("empty_recovery_run_id", payload))

    payload = copy.deepcopy(intent)
    del payload["operation_id"]
    mutations.append(("missing_required_operation_id", payload))

    payload = copy.deepcopy(intent)
    payload["op_schema"] = "UNKNOWN"
    mutations.append(("unknown_schema_marker", payload))

    payload = copy.deepcopy(intent)
    payload["record_type"] = "not_recovery_operation"
    mutations.append(("wrong_record_type", payload))

    payload = copy.deepcopy(intent)
    payload["phase"] = "ILLEGAL"
    mutations.append(("unknown_phase", payload))

    payload = copy.deepcopy(intent)
    payload["registered_at"] = "2026-01-01T00:00:00"
    mutations.append(("naive_registered_at", payload))

    payload = copy.deepcopy(intent)
    payload["registered_at"] = "not-a-time"
    mutations.append(("malformed_registered_at", payload))

    payload = copy.deepcopy(intent)
    payload["before_state"] = "[1,2,3]"
    mutations.append(("non_object_state_field", payload))

    payload = copy.deepcopy(intent)
    payload["operation_id"] = "0" * 64
    mutations.append(("operation_identity_mismatch", payload))

    payload = copy.deepcopy(intent)
    payload["recovery_operation_id"] = "wrong:INTENT"
    mutations.append(("phase_qualified_identity_mismatch", payload))

    payload = copy.deepcopy(effect)
    payload["effect_identity"] = None
    mutations.append(("effect_missing_identity", payload))

    payload = copy.deepcopy(effect)
    payload["effect_detail_sha256"] = "0" * 64
    mutations.append(("effect_detail_digest_mismatch", payload))

    payload = copy.deepcopy(effect)
    payload["recovery_operation_id"] = (
        f"{payload['operation_id']}:EFFECT_COMMITTED:" + "a" * 16
    )
    mutations.append(("truncated_effect_detail_key", payload))

    payload = copy.deepcopy(intent)
    payload["phase"] = "COMPLETED"
    payload["recovery_operation_id"] = f"{payload['operation_id']}:COMPLETED"
    payload["final_action_id"] = None
    mutations.append(("terminal_missing_final_action_id", payload))

    cases = [
        _case(
            name,
            rejected_closed=_rejected(payload),
            result=_OK if _rejected(payload) else _FAIL,
        )
        for name, payload in mutations
    ]
    assert len(cases) == 14
    return {
        "matrix": "BLOC_04_I08R2_OPERATION_RECORD_INTEGRITY_MATRIX",
        "checkpoint": "SENSOR-B4-I08R2",
        "doctrine": (
            "I08R2 §§13-14,23 — complete envelopes are recomputed and "
            "validated; exact retry compares every semantic field except "
            "registration time; malformed/tampered records fail closed"
        ),
        "cases": cases,
    }


class _OwnerRepo:
    def __init__(self) -> None:
        self._lock_owners: dict[str, dict[str, Any]] = {}
        self._job_locks: dict[str, threading.RLock] = {}

    def lock_for(self, job_id: str) -> threading.RLock:
        return self._job_locks.setdefault(job_id, threading.RLock())


def _lock(root: Path, job_id: str) -> tuple[str, Path]:
    lock_id = hashlib.sha256(job_id.encode("utf-8")).hexdigest()
    path = root / "locks" / f"{lock_id}.lock"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"stale lock\n")
    return lock_id, path


def _clear(
    root: Path,
    job_id: str,
    *,
    run_id: str,
    owner: _OwnerRepo | None = None,
) -> tuple[rec.RecoveryEngine, str, Path]:
    stack = Stack(root)
    lock_id, path = _lock(root, job_id)
    engine = stack.engine(run_id)
    engine.clear_job_lock(
        lock_id,
        expected_job_id=job_id,
        owner_repository=owner or _OwnerRepo(),
        run_id=run_id,
    )
    return engine, lock_id, path


def measure_i08r2_lock_clear_atomicity_matrix(tmp: Path) -> dict[str, Any]:
    """Corrected live measurement of the historical I08R2 lock scenarios.

    This function no longer regenerates the committed R2 matrix. R2R1
    consumes the corrected measurements under a new evidence identity; the
    old false-green bytes remain immutable historical evidence.
    """
    cases: list[dict[str, Any]] = []

    # Successful order captured at real method boundaries.
    root = tmp / "success"
    stack = Stack(root)
    job_id = "lock-success"
    lock_id, path = _lock(root, job_id)
    engine = stack.engine("lock-success-run")
    order: list[str] = []
    for method, label in (
        ("_record_intent", "INTENT"),
        ("_record_effect", "EFFECT"),
        ("_journal_action", "ACTION"),
        ("_record_outcome", "TERMINAL"),
    ):
        original = getattr(engine, method)

        def wrapper(*args: Any, _label: str = label, _original: Any = original, **kwargs: Any) -> Any:
            order.append(_label)
            return _original(*args, **kwargs)

        setattr(engine, method, wrapper)
    engine.clear_job_lock(
        lock_id,
        expected_job_id=job_id,
        owner_repository=_OwnerRepo(),
        run_id="lock-success-run",
    )
    cases.append(
        _case(
            "successful_clear_order",
            order=order,
            lock_absent=not path.exists(),
            result=_OK if order == ["INTENT", "EFFECT", "ACTION", "TERMINAL"] else _FAIL,
        )
    )

    # Missing repository.
    root = tmp / "missing-owner"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-missing-owner"
    lock_id, path = _lock(root, job_id)
    engine = stack.engine("lock-missing-owner-run")
    try:
        engine.clear_job_lock(
            lock_id,
            expected_job_id=job_id,
            owner_repository=None,
            run_id="lock-missing-owner-run",
        )
        refused = False
    except rec.RecoveryConfigurationError:
        refused = True
    cases.append(
        _case(
            "missing_owner_repository_refused",
            typed_refusal=refused,
            lock_intact=path.exists(),
            result=_OK if refused and path.exists() else _FAIL,
        )
    )

    # Wrong fingerprint.
    root = tmp / "wrong-fingerprint"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-wrong-fingerprint"
    _lock_id, path = _lock(root, job_id)
    engine = stack.engine("lock-wrong-run")
    try:
        engine.clear_job_lock(
            "0" * 64,
            expected_job_id=job_id,
            owner_repository=_OwnerRepo(),
            run_id="lock-wrong-run",
        )
        refused = False
    except rec.RecoveryConfigurationError:
        refused = True
    cases.append(
        _case(
            "wrong_lock_fingerprint_refused",
            typed_refusal=refused,
            lock_intact=path.exists(),
            result=_OK if refused and path.exists() else _FAIL,
        )
    )

    # Live owner map.
    root = tmp / "live-owner"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-live-owner"
    lock_id, path = _lock(root, job_id)
    owner = _OwnerRepo()
    owner._lock_owners[job_id] = {"thread": "live", "depth": 1}
    engine = stack.engine("lock-live-owner-run")
    try:
        engine.clear_job_lock(
            lock_id,
            expected_job_id=job_id,
            owner_repository=owner,
            run_id="lock-live-owner-run",
        )
        refused = False
    except rec.RecoveryPlanConflict:
        refused = True
    cases.append(
        _case(
            "live_owner_refused",
            typed_refusal=refused,
            lock_intact=path.exists(),
            result=_OK if refused and path.exists() else _FAIL,
        )
    )

    # RLock held by another thread.
    root = tmp / "held-rlock"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-held-rlock"
    lock_id, path = _lock(root, job_id)
    owner = _OwnerRepo()
    gate = owner.lock_for(job_id)
    held = threading.Event()
    release = threading.Event()

    def hold() -> None:
        with gate:
            held.set()
            release.wait(5)

    thread = threading.Thread(target=hold)
    thread.start()
    assert held.wait(5)
    engine = stack.engine("lock-held-run")
    try:
        engine.clear_job_lock(
            lock_id,
            expected_job_id=job_id,
            owner_repository=owner,
            run_id="lock-held-run",
        )
        refused = False
    except rec.RecoveryPlanConflict:
        refused = True
    finally:
        release.set()
        thread.join(5)
    cases.append(
        _case(
            "held_job_rlock_refused",
            typed_refusal=refused,
            lock_intact=path.exists(),
            result=_OK if refused and path.exists() else _FAIL,
        )
    )

    # Owner appears after INTENT and before unlink.
    root = tmp / "owner-race"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-owner-race"
    lock_id, path = _lock(root, job_id)
    owner = _OwnerRepo()
    engine = stack.engine("lock-owner-race-run")
    original_intent = engine._record_intent

    def intent_then_owner(*args: Any, **kwargs: Any) -> str:
        op_id = original_intent(*args, **kwargs)
        owner._lock_owners[job_id] = {"thread": "raced", "depth": 1}
        return op_id

    engine._record_intent = intent_then_owner  # type: ignore[method-assign]
    try:
        engine.clear_job_lock(
            lock_id,
            expected_job_id=job_id,
            owner_repository=owner,
            run_id="lock-owner-race-run",
        )
        refused = False
    except rec.RecoveryPlanConflict:
        refused = True
    rows = engine.operations.list_for_object(rec.SEMANTIC_JOB_LOCK, lock_id)
    cases.append(
        _case(
            "ownership_revalidated_after_intent",
            typed_refusal=refused,
            intent_durable=[row["phase"] for row in rows] == ["INTENT"],
            no_action=not engine.journal.list_for_object(
                rec.SEMANTIC_JOB_LOCK, lock_id
            ),
            lock_intact=path.exists(),
            result=_OK if refused and path.exists() else _FAIL,
        )
    )

    # Crash after unlink, before EFFECT: restart recognizes exact INTENT.
    class _DeadAfterUnlink(RuntimeError):
        pass

    root = tmp / "crash-after-unlink"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-crash-after-unlink"
    lock_id, path = _lock(root, job_id)
    engine = stack.engine("lock-run-a")

    def die(*args: Any, **kwargs: Any) -> None:
        raise _DeadAfterUnlink

    engine._record_effect = die  # type: ignore[method-assign]
    try:
        engine.clear_job_lock(
            lock_id,
            expected_job_id=job_id,
            owner_repository=_OwnerRepo(),
            run_id="lock-run-a",
        )
        died = False
    except _DeadAfterUnlink:
        died = True
    restarted = Stack(root).engine("lock-run-b")
    applied = restarted.apply_plan(
        restarted.scan(recovery_run_id="lock-run-b"),
        recovery_run_id="lock-run-b",
    )
    replay_report = restarted.last_replay_report
    rows = restarted.operations.list_for_object(rec.SEMANTIC_JOB_LOCK, lock_id)
    actions = restarted.journal.list_for_object(rec.SEMANTIC_JOB_LOCK, lock_id)
    injected_death = died
    lock_absent = not path.exists()
    original_run = {row["recovery_run_id"] for row in rows} == {"lock-run-a"}
    completed = sum(row["phase"] == "COMPLETED" for row in rows) == 1
    one_action = len(actions) == 1
    replay_closed = any(
        row["disposition"] == "CLOSED_EFFECT_PROVEN_LANDED"
        for row in replay_report
    )
    apply_return_is_not_replay_report = applied == [] and bool(replay_report)
    cases.append(
        _case(
            "crash_after_unlink_replays_original",
            injected_death=injected_death,
            lock_absent=lock_absent,
            original_run=original_run,
            completed=completed,
            one_action=one_action,
            replay_closed=replay_closed,
            apply_return_is_not_replay_report=apply_return_is_not_replay_report,
            required_invariants=[
                "injected_death",
                "lock_absent",
                "original_run",
                "completed",
                "one_action",
                "replay_closed",
                "apply_return_is_not_replay_report",
            ],
            result=_OK
            if all(
                (
                    injected_death,
                    lock_absent,
                    original_run,
                    completed,
                    one_action,
                    replay_closed,
                    apply_return_is_not_replay_report,
                )
            )
            else _FAIL,
        )
    )

    # Repeated restart does not duplicate clear evidence.
    restarted2 = Stack(root).engine("lock-run-c")
    restarted2.apply_plan(
        restarted2.scan(recovery_run_id="lock-run-c"),
        recovery_run_id="lock-run-c",
    )
    rows2 = restarted2.operations.list_for_object(rec.SEMANTIC_JOB_LOCK, lock_id)
    actions2 = restarted2.journal.list_for_object(rec.SEMANTIC_JOB_LOCK, lock_id)
    cases.append(
        _case(
            "repeated_lock_restart_stable",
            one_action=len(actions2) == 1,
            one_operation=len({row["operation_id"] for row in rows2}) == 1,
            original_run_preserved={row["recovery_run_id"] for row in rows2}
            == {"lock-run-a"},
            result=_OK if len(actions2) == 1 else _FAIL,
        )
    )

    # No-action INTENT while lock remains is not falsely completed.
    root = tmp / "open-intent"
    root.mkdir(parents=True)
    stack = Stack(root)
    job_id = "lock-open-intent"
    lock_id, path = _lock(root, job_id)
    engine = stack.engine("lock-open-run")
    planned = rec.RecoveryPlanAction(
        action_kind=rec._ACTION_OPERATE_CLEAR_JOB_LOCK,
        object_type=rec.SEMANTIC_JOB_LOCK,
        object_id=lock_id,
        problem=rec.PROBLEM_LOCK_PRESENT_OWNER_UNPROVEN,
        resolution="explicit operator clear with proven-absent ownership",
        before_state={"relative_path": f"locks/{lock_id}.lock"},
    )
    engine._record_intent(
        planned,
        "lock-open-run",
        effect_plan={
            "reconciliation": "OPERATOR_LOCK_CLEAR",
            "lock_fingerprint": lock_id,
            "expected_job_id": job_id,
            "relative_path": f"locks/{lock_id}.lock",
        },
    )
    restarted = Stack(root).engine("lock-open-restart")
    # Isolate restart replay from the still-present lock's legitimate
    # record-only scan action.  The interrupted explicit-clear operation
    # itself must acquire no action and remain open.
    empty = rec.RecoveryScanResult(
        recovery_run_id="lock-open-restart",
        findings=(),
        counts_by_problem={},
        has_blockers=False,
        planned_actions=(),
    )
    applied = restarted.apply_plan(empty, recovery_run_id="lock-open-restart")
    replay_report = restarted.last_replay_report
    rows = restarted.operations.list_for_object(rec.SEMANTIC_JOB_LOCK, lock_id)
    left_open = not any(
        row["phase"] in {"COMPLETED", "UNRESOLVED"} for row in rows
    )
    no_action = not restarted.journal.list_for_object(
        rec.SEMANTIC_JOB_LOCK, lock_id
    )
    lock_intact = path.exists()
    report_left_open = any(
        row["disposition"] == "LEFT_OPEN_NO_PROVEN_EFFECT"
        for row in replay_report
    )
    apply_return_is_not_replay_report = applied == [] and bool(replay_report)
    cases.append(
        _case(
            "present_lock_intent_not_false_completed",
            left_open=left_open,
            no_action=no_action,
            lock_intact=lock_intact,
            report_left_open=report_left_open,
            apply_return_is_not_replay_report=apply_return_is_not_replay_report,
            required_invariants=[
                "left_open",
                "no_action",
                "lock_intact",
                "report_left_open",
                "apply_return_is_not_replay_report",
            ],
            result=_OK
            if all(
                (
                    left_open,
                    no_action,
                    lock_intact,
                    report_left_open,
                    apply_return_is_not_replay_report,
                )
            )
            else _FAIL,
        )
    )
    assert len(cases) == 9
    return {
        "matrix": "BLOC_04_I08R2_LOCK_CLEAR_ATOMICITY_MATRIX",
        "checkpoint": "SENSOR-B4-I08R2",
        "doctrine": (
            "I08R2 §§17-18,24 — explicit lock clear is INTENT → live owner "
            "revalidation → unlink/fsync → EFFECT → final action → COMPLETED; "
            "restart recognizes absence only from the exact INTENT fingerprint"
        ),
        "cases": cases,
    }


def build_i08r2_lock_clear_atomicity_matrix_historical(tmp: Path) -> dict[str, Any]:
    """Frozen I08R2 false-green evidence; never regenerated after operator review."""
    del tmp
    return json.loads(
        (EVIDENCE_DIR / "BLOC_04_I08R2_LOCK_CLEAR_ATOMICITY_MATRIX.json").read_text(
            encoding="utf-8"
        )
    )


BUILDERS = [
    (
        build_i08r2_operation_terminality_matrix,
        "BLOC_04_I08R2_OPERATION_TERMINALITY_MATRIX.json",
    ),
    (
        build_i08r2_operation_record_integrity_matrix,
        "BLOC_04_I08R2_OPERATION_RECORD_INTEGRITY_MATRIX.json",
    ),
    (
        build_i08r2_lock_clear_atomicity_matrix_historical,
        "BLOC_04_I08R2_LOCK_CLEAR_ATOMICITY_MATRIX.json",
    ),
]


@pytest.mark.parametrize("builder,filename", BUILDERS)
def test_generated_matches_committed(
    builder: Any, filename: str, tmp_path: Path
) -> None:
    committed = (EVIDENCE_DIR / filename).read_bytes()
    assert stable_evidence_bytes(builder(tmp_path / builder.__name__)) == committed


def test_evidence_directory_untouched_after_run(tmp_path: Path) -> None:
    before = {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in EVIDENCE_DIR.glob("BLOC_04_I08R2_*.json")
    }
    for builder, _filename in BUILDERS:
        builder(tmp_path / builder.__name__)
    after = {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in EVIDENCE_DIR.glob("BLOC_04_I08R2_*.json")
    }
    assert before == after


if __name__ == "__main__":
    import tempfile

    publish_root = Path(tempfile.mkdtemp(prefix="i08r2-evidence-"))
    for builder, filename in BUILDERS:
        target = EVIDENCE_DIR / filename
        if target.exists():
            print(f"REFUSING to overwrite committed {filename}")
            continue
        target.write_bytes(
            stable_evidence_bytes(builder(publish_root / builder.__name__))
        )
        print(f"PUBLISHED {filename}")
