"""XHS data providers.

Built-in providers (Phase 3):
  - SyntheticProvider — synthetic data generated by scripts/gen_synthetic_data.py
  - CSVProvider — load from user-exported CSV
  - JSONProvider — load from local JSON dumps
  - OpenAPIProvider — any REST API conforming to OpenAPI 3.0 + mapping config

See docs/en/platforms/writing-a-provider.md for the interface contract.
"""
