"""CSIA Book 1 — package kernel exports.

Book 1 implementation (ratified plan v0.3):
- Bloc 1A canonical identity (``identity``)
- Bloc 1B node ontology (``ontology``)
- Bloc 1C relationships + hyperedges (``relationships``)
- Bloc 1D bitemporal model (``temporal``)

Planning authority: Constitution v0.2 RATIFIED + Book 1 plan v0.3 RATIFIED
(operator authorization 2026-09-23). Implementation authority is kernel-scope
only; no collectors, no persistence engines, no Book 2+ scope.
"""

from .identity import (
    Alias,
    CanonicalObject,
    DeploymentIdentity,
    DeploymentMarkerKind,
    DeploymentStatus,
    IdentityRegistry,
    IdentityResolutionEvent,
    ObjectType,
    RealizationIdentity,
    RealizationRoute,
    RepresentationMechanism,
    RouteHop,
    TickerSymbol,
    mint_deployment_id,
    mint_object_id,
    mint_realization_id,
)
from .ontology import (
    ArchitectureSlot,
    FamilySlotRegistry,
    RoleTag,
    role_tag,
)
from .relationships import (
    ChainScope,
    ChainScopeKind,
    EdgeSpec,
    EdgeType,
    GraphValidator,
    Hyperedge,
    HyperedgeClass,
    HyperedgeRole,
    RouteAttributes,
    RouteMechanism,
    SecurityMechanism,
    TypedEdge,
    edge_spec,
)
from .temporal import (
    OPEN,
    ClaimBinding,
    ObjectLifecycle,
    RealizationStatus,
    RecordLifecycle,
    RecordStore,
    TemporalRecord,
    UnknownBound,
    holds_at,
    normalize_utc,
    utc_now,
)
from .types import AuthoritySeed, AuthorityTier, ClaimFamily, SourceClass
from .sources import (
    AccessMethod,
    LocatorMetadata,
    Source,
    SourceHealth,
    SourceLifecycle,
    SourceRegistry,
    VerificationStatus,
)
from .evidence import (
    EvidenceStatus,
    EvidenceStore,
    EvidenceTier,
    RawEvidence,
    TimeHint,
    canonical_bytes,
    content_hash_for,
)
from .acquisition import (
    AcquisitionContract,
    AcquisitionContractBook,
    AcquisitionObservation,
    AcquisitionType,
    AuthenticationKind,
    AuthenticationMetadata,
    CostMetadata,
    FailureState,
    RateLimitPolicy,
    RetrievalSemantics,
    RetryPolicy,
    SchemaDriftBehavior,
    SnapshotPolicy,
)
from .authority import (
    AuthorityAssignment,
    AuthorityDecision,
    AuthorityKey,
    AuthorityPolicy,
    AuthorityResolution,
    DiscrepancyEvent,
)
from .claims import (
    Claim,
    ClaimService,
    ClaimState,
    ClaimStore,
    InferenceEngine,
    Methodology,
    MethodologyParameter,
    Proposition,
    SupersessionLineage,
    TransitionEvent,
)
from .promotion import ClaimStateEngine, IllegalClaimTransition, LEGAL_TRANSITIONS
from .contradiction import ContradictionEngine, ContradictionResolution, ResolutionKind
from .freshness import (
    FreshnessEvaluation,
    FreshnessMode,
    FreshnessPolicy,
    FreshnessPolicyBook,
    StalenessKind,
)
from .changes import ChangeCandidate, ChangeCandidateStore, ChangeClass
from .research_interface import CorroborationMaterial, ResearchInterface, ResearchOperation

__version__ = "0.4.0"

__all__ = [
    "OPEN",
    "AccessMethod",
    "AcquisitionContract",
    "AcquisitionContractBook",
    "AcquisitionObservation",
    "AcquisitionType",
    "Alias",
    "ArchitectureSlot",
    "AuthorityAssignment",
    "AuthorityDecision",
    "AuthorityKey",
    "AuthorityPolicy",
    "AuthorityResolution",
    "AuthoritySeed",
    "AuthorityTier",
    "AuthenticationKind",
    "AuthenticationMetadata",
    "CanonicalObject",
    "ChainScope",
    "ChainScopeKind",
    "ChangeCandidate",
    "ChangeCandidateStore",
    "ChangeClass",
    "Claim",
    "ClaimBinding",
    "ClaimFamily",
    "ClaimService",
    "ClaimState",
    "ClaimStateEngine",
    "ClaimStore",
    "ContradictionEngine",
    "ContradictionResolution",
    "CorroborationMaterial",
    "CostMetadata",
    "DeploymentIdentity",
    "DeploymentMarkerKind",
    "DeploymentStatus",
    "DiscrepancyEvent",
    "EdgeSpec",
    "EdgeType",
    "EvidenceStatus",
    "EvidenceStore",
    "EvidenceTier",
    "FailureState",
    "FamilySlotRegistry",
    "FreshnessEvaluation",
    "FreshnessMode",
    "FreshnessPolicy",
    "FreshnessPolicyBook",
    "GraphValidator",
    "Hyperedge",
    "HyperedgeClass",
    "HyperedgeRole",
    "IdentityRegistry",
    "IdentityResolutionEvent",
    "IllegalClaimTransition",
    "InferenceEngine",
    "LEGAL_TRANSITIONS",
    "LocatorMetadata",
    "Methodology",
    "MethodologyParameter",
    "ObjectLifecycle",
    "ObjectType",
    "Proposition",
    "RateLimitPolicy",
    "RawEvidence",
    "RealizationIdentity",
    "RealizationRoute",
    "RealizationStatus",
    "RecordLifecycle",
    "RecordStore",
    "RepresentationMechanism",
    "ResearchInterface",
    "ResearchOperation",
    "ResolutionKind",
    "RetrievalSemantics",
    "RetryPolicy",
    "RoleTag",
    "RouteAttributes",
    "RouteHop",
    "RouteMechanism",
    "SchemaDriftBehavior",
    "SecurityMechanism",
    "SnapshotPolicy",
    "Source",
    "SourceClass",
    "SourceHealth",
    "SourceLifecycle",
    "SourceRegistry",
    "StalenessKind",
    "SupersessionLineage",
    "TemporalRecord",
    "TickerSymbol",
    "TimeHint",
    "TransitionEvent",
    "TypedEdge",
    "UnknownBound",
    "VerificationStatus",
    "canonical_bytes",
    "content_hash_for",
    "edge_spec",
    "holds_at",
    "mint_deployment_id",
    "mint_object_id",
    "mint_realization_id",
    "normalize_utc",
    "role_tag",
    "utc_now",
]
