"""Book 6 validation traceability — every row bound to a real assertion.

A traceability matrix is only worth anything if each row names an assertion that
actually exists. Every row below cites a concrete pytest node id, and
``test_book6_traceability.py`` resolves every one of them against the test files
on disk, so a row cannot outlive the assertion it claims to trace to.

The ratified 6D families are covered mechanically:

- **6D.1** missingness — ten states, ``ZERO_OBSERVED != missing``, no fabricated
  zero, and fail-closed quotients;
- **6D.2** methodology sensitivity — two reasonable methodologies may disagree
  and the disagreement is surfaced, never resolved;
- **6D.3** historical sanity — append-preserving revision, linear supersession,
  window-bounded reorgs, and deterministic replay;
- **6D.4** cross-source parity — source-specific measurements preserved, no
  consensus number, no invented tolerance;
- **6D.5** false-comparison detection — all fifteen ratified corpus rows gated.

plus the two structural firewalls (anti-score, D2-6) and state-rule integrity.
"""

from __future__ import annotations

from typing import Final

#: The ratified 6D validation families.
VALIDATION_FAMILIES: Final[tuple[str, ...]] = ("6D.1", "6D.2", "6D.3", "6D.4", "6D.5")

#: The structural gates that are not part of the 6D corpus but must be traced.
STRUCTURAL_FAMILIES: Final[tuple[str, ...]] = (
    "FIREWALL.ANTI_SCORE",
    "FIREWALL.D2_6",
    "STATE_RULE_INTEGRITY",
    "MEASUREMENT_KERNEL",
    "NORMALIZATION_LINEAGE",
    "VALUATION_SEAM",
    "METRIC_FAMILIES",
)

#: ``(row_id, family, claim, test_file, test_name)``. Every row must resolve.
TRACEABILITY_ROWS: Final[tuple[tuple[str, str, str, str, str], ...]] = (
    # -- 6D.1 missingness ---------------------------------------------------
    (
        "6D.1.01",
        "6D.1",
        "ten distinct missingness states exist and none collapses into another",
        "test_book6_missingness.py",
        "test_ten_distinct_missingness_states",
    ),
    (
        "6D.1.02",
        "6D.1",
        "ZERO_OBSERVED is a measured zero and is not any form of absence",
        "test_book6_missingness.py",
        "test_zero_observed_is_distinct_from_every_absence",
    ),
    (
        "6D.1.03",
        "6D.1",
        "a missingness state that forbids a value may never carry a fabricated zero",
        "test_book6_missingness.py",
        "test_absence_may_never_carry_a_fabricated_zero",
    ),
    (
        "6D.1.04",
        "6D.1",
        "an absent observation carries no value at all",
        "test_book6_missingness.py",
        "test_absence_carries_no_value_at_all",
    ),
    (
        "6D.1.05",
        "6D.1",
        "the engine refuses to read a value out of an absence",
        "test_book6_missingness.py",
        "test_engine_refuses_to_read_a_value_out_of_an_absence",
    ),
    (
        "6D.1.06",
        "6D.1",
        "six distinct denominator states exist",
        "test_book6_missingness.py",
        "test_denominator_states_are_distinct",
    ),
    (
        "6D.1.07",
        "6D.1",
        "an observed-zero denominator yields an undefined ratio, never infinity",
        "test_book6_missingness.py",
        "test_observed_zero_denominator_yields_undefined_not_infinity",
    ),
    (
        "6D.1.08",
        "6D.1",
        "a missing denominator never produces a ratio",
        "test_book6_missingness.py",
        "test_missing_denominator_never_produces_a_ratio",
    ),
    (
        "6D.1.09",
        "6D.1",
        "a coverage observation can never assert sufficiency on its own",
        "test_book6_missingness.py",
        "test_coverage_percentage_asserts_no_sufficiency",
    ),
    # -- 6D.2 methodology sensitivity ---------------------------------------
    (
        "6D.2.01",
        "6D.2",
        "disagreeing methodologies are surfaced as METHODOLOGY_SENSITIVE",
        "test_book6_sensitivity.py",
        "test_disagreeing_methodologies_are_reported_sensitive",
    ),
    (
        "6D.2.02",
        "6D.2",
        "a sensitivity finding names no preferred, best or canonical methodology",
        "test_book6_sensitivity.py",
        "test_a_sensitive_finding_names_no_winner",
    ),
    (
        "6D.2.03",
        "6D.2",
        "each variant retains its own methodology identity",
        "test_book6_sensitivity.py",
        "test_each_variant_keeps_its_own_methodology_identity",
    ),
    (
        "6D.2.04",
        "6D.2",
        "an unobserved variant makes the comparison UNDETERMINED, not zero",
        "test_book6_sensitivity.py",
        "test_an_unobserved_variant_makes_the_comparison_undetermined_not_zero",
    ),
    (
        "6D.2.05",
        "6D.2",
        "a finding carries no numeric severity",
        "test_book6_sensitivity.py",
        "test_sensitivity_finding_carries_no_numeric_severity",
    ),
    (
        "6D.2.06",
        "6D.2",
        "all five ratified methodology divergences are surfaced (accounts, volume, fees, developers, capital)",
        "test_book6_sensitivity.py",
        "test_each_ratified_methodology_divergence_is_surfaced",
    ),
    # -- 6D.3 historical sanity --------------------------------------------
    (
        "6D.3.01",
        "6D.3",
        "a restatement creates a new observation rather than overwriting the prior one",
        "test_book6_temporal.py",
        "test_a_restatement_creates_a_new_observation_rather_than_overwriting",
    ),
    (
        "6D.3.02",
        "6D.3",
        "supersession is linear and ordered",
        "test_book6_temporal.py",
        "test_the_supersession_chain_is_linear_and_ordered",
    ),
    (
        "6D.3.03",
        "6D.3",
        "a forked supersession chain is refused",
        "test_book6_temporal.py",
        "test_a_forked_supersession_chain_is_refused",
    ),
    (
        "6D.3.04",
        "6D.3",
        "history is retained across many revisions",
        "test_book6_temporal.py",
        "test_history_is_retained_across_many_revisions",
    ),
    (
        "6D.3.05",
        "6D.3",
        "a chain reorg is window-bounded and does not rewrite the whole history",
        "test_book6_temporal.py",
        "test_a_reorg_is_window_bounded",
    ),
    (
        "6D.3.06",
        "6D.3",
        "a methodology change creates a new version, never an in-place edit",
        "test_book6_temporal.py",
        "test_a_methodology_change_creates_a_new_version_not_an_edit",
    ),
    (
        "6D.3.07",
        "6D.3",
        "the same sequence replays to the same history",
        "test_book6_temporal.py",
        "test_the_same_sequence_replays_to_the_same_history",
    ),
    (
        "6D.3.08",
        "6D.3",
        "replay does not depend on wall-clock time",
        "test_book6_temporal.py",
        "test_replay_does_not_depend_on_wall_clock_time",
    ),
    (
        "6D.3.09",
        "6D.3",
        "valid time and observed time are independent axes",
        "test_book6_temporal.py",
        "test_observed_at_and_valid_time_are_independent_axes",
    ),
    (
        "6D.3.10",
        "6D.3",
        "a stale Book 2 claim decays the citing measurement's authority",
        "test_book6_temporal.py",
        "test_a_stale_claim_decays_the_measurement_authority",
    ),
    (
        "6D.3.11",
        "6D.3",
        "where Book 2 legally restores authority, Book 6 restores too",
        "test_book6_temporal.py",
        "test_where_book_2_restores_authority_book_6_restores_too",
    ),
    (
        "6D.3.12",
        "6D.3",
        "a decayed measurement survives as queryable history",
        "test_book6_temporal.py",
        "test_the_record_survives_the_decay_as_queryable_history",
    ),
    (
        "6D.3.13",
        "6D.3",
        "partial Book 2 authority grants nothing",
        "test_book6_temporal.py",
        "test_a_partial_authority_grants_nothing",
    ),
    (
        "6D.3.14",
        "6D.3",
        "a stale current price makes a current valuation unavailable",
        "test_book6_temporal.py",
        "test_a_stale_price_makes_the_current_valuation_unavailable",
    ),
    (
        "6D.3.15",
        "6D.3",
        "current unavailability is not historical invalidity (bitemporal)",
        "test_book6_temporal.py",
        "test_currently_unavailable_is_not_historically_invalid",
    ),
    (
        "6D.3.16",
        "6D.3",
        "a source-unavailable price is absent, not zero",
        "test_book6_temporal.py",
        "test_a_source_unavailable_price_is_absent_not_zero",
    ),
    (
        "6D.3.17",
        "6D.3",
        "a market-closed price is stale, not invalid",
        "test_book6_temporal.py",
        "test_a_market_closed_price_is_stale_not_invalid",
    ),
    # -- 6D.4 cross-source parity -------------------------------------------
    (
        "6D.4.01",
        "6D.4",
        "agreeing sources are reported as agreeing",
        "test_book6_sensitivity.py",
        "test_sources_that_agree_are_reported_agreeing",
    ),
    (
        "6D.4.02",
        "6D.4",
        "divergent sources are reported as diverging and both values are preserved",
        "test_book6_sensitivity.py",
        "test_divergent_sources_are_reported_diverging_and_preserved",
    ),
    (
        "6D.4.03",
        "6D.4",
        "no consensus value is computed from divergent sources",
        "test_book6_sensitivity.py",
        "test_no_consensus_value_is_computed_from_divergent_sources",
    ),
    (
        "6D.4.04",
        "6D.4",
        "the module offers no averaging, median or blending helper",
        "test_book6_sensitivity.py",
        "test_the_module_offers_no_averaging_helper",
    ),
    (
        "6D.4.05",
        "6D.4",
        "an absent source is not a source that agrees",
        "test_book6_sensitivity.py",
        "test_an_absent_source_is_not_a_source_that_agrees",
    ),
    (
        "6D.4.06",
        "6D.4",
        "no tolerance is invented; near-equal floats are reported as divergence",
        "test_book6_sensitivity.py",
        "test_no_tolerance_is_invented_for_float_agreement",
    ),
    # -- 6D.5 false-comparison detection -------------------------------------
    (
        "6D.5.01",
        "6D.5",
        "the corpus carries the fifteen ratified rows",
        "test_book6_comparability.py",
        "test_corpus_has_the_fifteen_ratified_rows",
    ),
    (
        "6D.5.02",
        "6D.5",
        "every operator-required comparison has a mechanized row",
        "test_book6_comparability.py",
        "test_every_required_operator_comparison_has_a_row",
    ),
    (
        "6D.5.03",
        "6D.5",
        "no corpus row is a bare comparable verdict",
        "test_book6_comparability.py",
        "test_no_row_is_a_bare_comparable_verdict",
    ),
    (
        "6D.5.04",
        "6D.5",
        "every ratified pair is refused without its named methodology",
        "test_book6_comparability.py",
        "test_every_ratified_pair_is_refused_without_its_methodology",
    ),
    (
        "6D.5.05",
        "6D.5",
        "a NOT_COMPARABLE pair stays refused even with a methodology",
        "test_book6_comparability.py",
        "test_not_comparable_pairs_stay_refused_even_with_a_methodology",
    ),
    (
        "6D.5.06",
        "6D.5",
        "an AS_DISTINCT pair is licensed only as separate metrics",
        "test_book6_comparability.py",
        "test_as_distinct_pairs_are_never_a_comparison",
    ),
    (
        "6D.5.07",
        "6D.5",
        "the gate is symmetric",
        "test_book6_comparability.py",
        "test_the_gate_is_symmetric",
    ),
    (
        "6D.5.08",
        "6D.5",
        "an ungoverned pair is refused rather than defaulted",
        "test_book6_comparability.py",
        "test_an_ungoverned_pair_is_refused_not_defaulted",
    ),
    (
        "6D.5.09",
        "6D.5",
        "a wildcard comparison is refused",
        "test_book6_comparability.py",
        "test_a_wildcard_comparison_is_refused",
    ),
    (
        "6D.5.10",
        "6D.5",
        "mismatched comparability classes are refused even under a named methodology",
        "test_book6_comparability.py",
        "test_comparability_classes_must_match_even_under_a_named_methodology",
    ),
    (
        "6D.5.11",
        "6D.5",
        "the engine routes every comparison through the same gate",
        "test_book6_comparability.py",
        "test_engine_comparison_goes_through_the_same_gate",
    ),
    # -- structural firewall: anti-score ------------------------------------
    (
        "FW.AS.01",
        "FIREWALL.ANTI_SCORE",
        "the vector declares no score, total, rating, grade or rank field",
        "test_book6_state_vector.py",
        "test_the_vector_has_no_score_fields",
    ),
    (
        "FW.AS.02",
        "FIREWALL.ANTI_SCORE",
        "constructor injection of a score field is refused",
        "test_book6_state_vector.py",
        "test_constructor_injection_of_an_anti_score_field_fails",
    ),
    (
        "FW.AS.03",
        "FIREWALL.ANTI_SCORE",
        "model_copy injection of a score field is refused, not smuggled",
        "test_book6_state_vector.py",
        "test_model_copy_injection_of_an_anti_score_field_is_refused",
    ),
    (
        "FW.AS.04",
        "FIREWALL.ANTI_SCORE",
        "raw dict deserialization of a score field is refused",
        "test_book6_state_vector.py",
        "test_raw_dict_deserialization_of_an_anti_score_field_fails",
    ),
    (
        "FW.AS.05",
        "FIREWALL.ANTI_SCORE",
        "a serialization round-trip injects nothing",
        "test_book6_state_vector.py",
        "test_a_serialization_round_trip_injects_nothing",
    ),
    (
        "FW.AS.06",
        "FIREWALL.ANTI_SCORE",
        "nested payload injection into a dimension is refused",
        "test_book6_state_vector.py",
        "test_nested_payload_injection_into_a_dimension_fails",
    ),
    (
        "FW.AS.07",
        "FIREWALL.ANTI_SCORE",
        "a nested dimension may not carry a prescriptive name",
        "test_book6_state_vector.py",
        "test_a_nested_dimension_cannot_carry_a_prescriptive_name",
    ),
    (
        "FW.AS.08",
        "FIREWALL.ANTI_SCORE",
        "no Book 6 record class declares a score field",
        "test_book6_state_vector.py",
        "test_no_book6_record_class_declares_a_score_field",
    ),
    (
        "FW.AS.09",
        "FIREWALL.ANTI_SCORE",
        "there is no numeric completeness score",
        "test_book6_state_vector.py",
        "test_there_is_no_numeric_completeness_score",
    ),
    # -- structural firewall: D2-6 -----------------------------------------
    (
        "FW.D26.01",
        "FIREWALL.D2_6",
        "no usage, health, retention, bot or adoption state exists",
        "test_book6_state_vector.py",
        "test_no_usage_health_state_exists",
    ),
    (
        "FW.D26.02",
        "FIREWALL.D2_6",
        "D6M-5 names are prohibited state names",
        "test_book6_state_vector.py",
        "test_d2_6_names_are_prohibited_state_names",
    ),
    (
        "FW.D26.03",
        "FIREWALL.D2_6",
        "no usage or health threshold appears on the Book 6 surface",
        "test_book6_state_vector.py",
        "test_no_usage_threshold_appears_anywhere_in_the_book6_surface",
    ),
    (
        "FW.D26.04",
        "FIREWALL.D2_6",
        "no D2-6 research executor exists anywhere in Book 6",
        "test_book6_adversarial.py",
        "test_no_d2_6_research_executor_exists_in_book6",
    ),
    # -- state-rule integrity -----------------------------------------------
    (
        "SR.01",
        "STATE_RULE_INTEGRITY",
        "INDIVIDUAL_STATE_RULES_RATIFIED is 0 at bootstrap",
        "test_book6_state_rules.py",
        "test_bootstrap_ratified_count_is_zero",
    ),
    (
        "SR.02",
        "STATE_RULE_INTEGRITY",
        "a fresh registry holds no rules at all",
        "test_book6_state_rules.py",
        "test_a_fresh_registry_holds_no_rules_at_all",
    ),
    (
        "SR.03",
        "STATE_RULE_INTEGRITY",
        "registering a rule does not ratify it",
        "test_book6_state_rules.py",
        "test_registering_a_rule_does_not_ratify_it",
    ),
    (
        "SR.04",
        "STATE_RULE_INTEGRITY",
        "no Class B or C state is emittable at bootstrap",
        "test_book6_state_rules.py",
        "test_no_class_b_or_c_state_is_emittable_at_bootstrap",
    ),
    (
        "SR.05",
        "STATE_RULE_INTEGRITY",
        "the engine refuses to emit any Class B or C state",
        "test_book6_state_rules.py",
        "test_the_engine_refuses_to_emit_any_class_b_or_c_state",
    ),
    (
        "SR.06",
        "STATE_RULE_INTEGRITY",
        "synthetic fixture ratification is local and never becomes canonical",
        "test_book6_state_rules.py",
        "test_synthetic_ratification_is_local_and_not_canonical",
    ),
    (
        "SR.07",
        "STATE_RULE_INTEGRITY",
        "there is no delegated, bulk or automatic ratification path",
        "test_book6_state_rules.py",
        "test_there_is_no_delegated_or_automatic_ratification_path",
    ),
    (
        "SR.08",
        "STATE_RULE_INTEGRITY",
        "Class A states are emittable with no rule and may not carry one",
        "test_book6_state_rules.py",
        "test_a_class_a_state_may_not_carry_a_rule",
    ),
    (
        "SR.09",
        "STATE_RULE_INTEGRITY",
        "generic EXPANDING/CONTRACTING are deferred and unwritable as a rule",
        "test_book6_state_rules.py",
        "test_no_rule_can_be_written_for_a_generic_state",
    ),
    (
        "SR.10",
        "STATE_RULE_INTEGRITY",
        "a new rule version does not inherit the prior ratification",
        "test_book6_state_rules.py",
        "test_a_new_version_does_not_inherit_the_prior_ratification",
    ),
    (
        "SR.11",
        "STATE_RULE_INTEGRITY",
        "a forged RATIFIED flag does not authorize a state",
        "test_book6_adversarial.py",
        "test_a_forged_ratified_flag_does_not_authorize_a_state",
    ),
    (
        "SR.12",
        "STATE_RULE_INTEGRITY",
        "an unregistered state rule is refused",
        "test_book6_state_rules.py",
        "test_an_unregistered_rule_ref_is_refused",
    ),
    (
        "SR.13",
        "STATE_RULE_INTEGRITY",
        "no data reports INSUFFICIENT_DATA rather than zero",
        "test_book6_state_rules.py",
        "test_no_data_reports_insufficient_data_not_zero",
    ),
    (
        "SR.14",
        "STATE_RULE_INTEGRITY",
        "unratified coverage sufficiency is reported, never assumed",
        "test_book6_state_rules.py",
        "test_unratified_coverage_sufficiency_is_reported_not_assumed",
    ),
    # -- measurement-kernel invariants --------------------------------------
    (
        "MK.01",
        "MEASUREMENT_KERNEL",
        "DATA_COMPLETE fails closed without a ratified coverage-sufficiency rule",
        "test_book6_state_vector.py",
        "test_fully_observed_dimensions_still_fail_closed_without_a_sufficiency_rule",
    ),
    (
        "MK.02",
        "MEASUREMENT_KERNEL",
        "no coverage-sufficiency rule exists to name at bootstrap",
        "test_book6_state_vector.py",
        "test_no_coverage_sufficiency_rule_exists_to_name_at_bootstrap",
    ),
    (
        "MK.03",
        "MEASUREMENT_KERNEL",
        "the twenty-one grammar categories remain distinct types and do not collapse",
        "test_book6_core.py",
        "test_grammar_categories_remain_distinct_types",
    ),
    (
        "MK.04",
        "MEASUREMENT_KERNEL",
        "COUNT is not FLOW, FLOW is not STOCK, RATE is not RATIO",
        "test_book6_core.py",
        "test_count_is_not_sum_and_flow_is_not_stock",
    ),
    (
        "MK.05",
        "MEASUREMENT_KERNEL",
        "NORMALIZED is a distinct measurement role, not a flag",
        "test_book6_core.py",
        "test_normalized_is_a_distinct_role",
    ),
    (
        "MK.06",
        "MEASUREMENT_KERNEL",
        "a MeasurementObservation is not a Book 2 claim (D6M-1 = A)",
        "test_book6_core.py",
        "test_measurement_is_not_a_book2_claim",
    ),
    (
        "MK.07",
        "MEASUREMENT_KERNEL",
        "the provenance adapter refuses a defaulted or disabled resolver",
        "test_book6_core.py",
        "test_book6_provenance_requires_explicit_resolver",
    ),
    (
        "MK.08",
        "MEASUREMENT_KERNEL",
        "an unknown Book 2 claim reference fails closed",
        "test_book6_core.py",
        "test_unknown_claim_ref_fails_closed",
    ),
    (
        "MK.09",
        "MEASUREMENT_KERNEL",
        "a value-bearing observation requires live Book 2 authority",
        "test_book6_core.py",
        "test_value_bearing_observation_requires_book2_authority",
    ),
    (
        "MK.10",
        "MEASUREMENT_KERNEL",
        "a metric name alone is not a definition",
        "test_book6_core.py",
        "test_metric_name_alone_is_not_a_definition",
    ),
    (
        "MK.11",
        "MEASUREMENT_KERNEL",
        "a ratio definition must declare its denominator rule",
        "test_book6_core.py",
        "test_ratio_definition_must_declare_denominator_rule",
    ),
    (
        "MK.12",
        "MEASUREMENT_KERNEL",
        "a cross-architecture class may not be scoped to specific families",
        "test_book6_core.py",
        "test_cross_architecture_class_may_not_be_scoped_to_families",
    ),
    (
        "MK.13",
        "MEASUREMENT_KERNEL",
        "architecture applicability is an explicit allow-list",
        "test_book6_core.py",
        "test_architecture_applicability_is_an_allow_list",
    ),
    (
        "MK.14",
        "MEASUREMENT_KERNEL",
        "a windowed metric requires an explicit interval",
        "test_book6_core.py",
        "test_windowed_metric_requires_explicit_interval",
    ),
    (
        "MK.15",
        "MEASUREMENT_KERNEL",
        "an instantaneous metric may not declare an interval",
        "test_book6_core.py",
        "test_instantaneous_metric_may_not_declare_interval",
    ),
    (
        "MK.16",
        "MEASUREMENT_KERNEL",
        "a value-bearing state requires both its value and its unit",
        "test_book6_core.py",
        "test_value_bearing_state_requires_value_and_unit",
    ),
    (
        "MK.17",
        "MEASUREMENT_KERNEL",
        "a measurement requires a registered definition and may not define its own metric",
        "test_book6_core.py",
        "test_measurement_requires_registered_definition",
    ),
    (
        "MK.18",
        "MEASUREMENT_KERNEL",
        "an observation drifting from its definition is refused",
        "test_book6_core.py",
        "test_observation_drifting_from_definition_is_refused",
    ),
    # -- normalization lineage (D6M-2 = B) ---------------------------------
    (
        "NL.01",
        "NORMALIZATION_LINEAGE",
        "the NormalizationRule contract binds every ratified field",
        "test_book6_normalization.py",
        "test_normalization_rule_requires_every_ratified_field",
    ),
    (
        "NL.02",
        "NORMALIZATION_LINEAGE",
        "normalization is not a field on the metric definition",
        "test_book6_normalization.py",
        "test_normalization_is_not_a_field_on_the_metric_definition",
    ),
    (
        "NL.03",
        "NORMALIZATION_LINEAGE",
        "normalization is not a field on the measurement observation",
        "test_book6_normalization.py",
        "test_normalization_is_not_a_field_on_the_measurement_observation",
    ),
    (
        "NL.04",
        "NORMALIZATION_LINEAGE",
        "a normalized product requires native lineage at construction",
        "test_book6_normalization.py",
        "test_normalized_product_requires_native_lineage_at_construction",
    ),
    (
        "NL.05",
        "NORMALIZATION_LINEAGE",
        "lineage pointed at a different native set is refused",
        "test_book6_normalization.py",
        "test_lineage_pointed_at_a_different_native_set_is_refused",
    ),
    (
        "NL.06",
        "NORMALIZATION_LINEAGE",
        "lineage cannot be widened by appending fabricated inputs",
        "test_book6_normalization.py",
        "test_lineage_cannot_be_widened_by_appending_fabricated_inputs",
    ),
    (
        "NL.07",
        "NORMALIZATION_LINEAGE",
        "model_copy cannot strip lineage and still authorize",
        "test_book6_normalization.py",
        "test_model_copy_cannot_strip_lineage_and_still_authorize",
    ),
    (
        "NL.08",
        "NORMALIZATION_LINEAGE",
        "NORMALIZED_WITHOUT_NATIVE_LINEAGE is invalid end to end",
        "test_book6_normalization.py",
        "test_normalized_without_native_lineage_is_invalid_end_to_end",
    ),
    (
        "NL.09",
        "NORMALIZATION_LINEAGE",
        "PERCENTILE is not a normalization type and cannot be built or injected",
        "test_book6_normalization.py",
        "test_percentile_cannot_be_constructed_even_as_a_raw_string",
    ),
    (
        "NL.10",
        "NORMALIZATION_LINEAGE",
        "a cohort-relative normalization must name its cohort",
        "test_book6_normalization.py",
        "test_cohort_relative_normalization_requires_a_cohort",
    ),
    (
        "NL.11",
        "NORMALIZATION_LINEAGE",
        "a dividing normalization must name its denominator",
        "test_book6_normalization.py",
        "test_dividing_normalization_requires_a_denominator",
    ),
    (
        "NL.12",
        "NORMALIZATION_LINEAGE",
        "cohort membership is explicit, never an implicit all-chains",
        "test_book6_normalization.py",
        "test_cohort_membership_is_explicit_not_implicit_all_chains",
    ),
    (
        "NL.13",
        "NORMALIZATION_LINEAGE",
        "normalization admissibility is scoped to the metric category",
        "test_book6_normalization.py",
        "test_per_user_is_invalid_for_a_ratio_metric",
    ),
    (
        "NL.14",
        "NORMALIZATION_LINEAGE",
        "a normalized product is never registered as a native measurement",
        "test_book6_normalization.py",
        "test_normalized_products_are_never_registered_as_native_measurements",
    ),
    # -- valuation seam (D6M-4 = A) -----------------------------------------
    (
        "VS.01",
        "VALUATION_SEAM",
        "a valuation requires an explicit numeraire with no default",
        "test_book6_valuation.py",
        "test_numeraire_is_required",
    ),
    (
        "VS.02",
        "VALUATION_SEAM",
        "USD is not the default numeraire",
        "test_book6_valuation.py",
        "test_usd_is_not_the_default_numeraire",
    ),
    (
        "VS.03",
        "VALUATION_SEAM",
        "no common value exists without an explicit cited price observation",
        "test_book6_valuation.py",
        "test_no_common_value_without_a_price_observation",
    ),
    (
        "VS.04",
        "VALUATION_SEAM",
        "price authority is purpose-specific across every ratified purpose",
        "test_book6_valuation.py",
        "test_price_authority_is_purpose_specific",
    ),
    (
        "VS.05",
        "VALUATION_SEAM",
        "no price class is admissible for every purpose, so no global winner exists",
        "test_book6_valuation.py",
        "test_no_price_class_is_admissible_for_every_purpose",
    ),
    (
        "VS.06",
        "VALUATION_SEAM",
        "divergent price classes are preserved side by side and never merged",
        "test_book6_valuation.py",
        "test_divergent_price_classes_are_preserved_side_by_side",
    ),
    (
        "VS.07",
        "VALUATION_SEAM",
        "there is no consensus price combinator",
        "test_book6_valuation.py",
        "test_there_is_no_consensus_price_combinator",
    ),
    (
        "VS.08",
        "VALUATION_SEAM",
        "the Book 5 write-back refusal is explicit and named",
        "test_book6_valuation.py",
        "test_book_5_write_back_is_explicitly_refused",
    ),
    (
        "VS.09",
        "VALUATION_SEAM",
        "no Book 6 module imports Book 5, so the seam is structurally write-free",
        "test_book6_valuation.py",
        "test_no_book6_api_writes_into_a_book_5_record",
    ),
    (
        "VS.10",
        "VALUATION_SEAM",
        "no Book 6 module imports the Book 4 dependency graph",
        "test_book6_valuation.py",
        "test_no_book6_measurement_api_can_rewrite_a_book_4_edge",
    ),
    (
        "VS.11",
        "VALUATION_SEAM",
        "no Book 6 API can rewrite a dependency edge",
        "test_book6_valuation.py",
        "test_no_book6_module_mutates_a_dependency_edge",
    ),
    (
        "VS.12",
        "VALUATION_SEAM",
        "the engine re-reads the numeraire at use, refusing a stripped copy",
        "test_book6_valuation.py",
        "test_engine_rejects_a_stripped_numeraire_that_reuses_an_admissible_price",
    ),
    (
        "VS.13",
        "VALUATION_SEAM",
        "the engine re-reads the price source at use, refusing a stripped copy",
        "test_book6_valuation.py",
        "test_engine_rejects_a_price_with_a_stripped_source",
    ),
    # -- metric families (Phase 28) -----------------------------------------
    (
        "MF.01",
        "METRIC_FAMILIES",
        "the five ratified 6A families exist as schema",
        "test_book6_families.py",
        "test_the_five_ratified_families_are_present",
    ),
    (
        "MF.02",
        "METRIC_FAMILIES",
        "no default metric is shipped and the registry holds no pre-registered definitions",
        "test_book6_families.py",
        "test_the_registry_ships_no_pre_registered_definitions",
    ),
    (
        "MF.03",
        "METRIC_FAMILIES",
        "a scoped definition is NOT_SUPPORTED outside its architectures",
        "test_book6_families.py",
        "test_a_scoped_definition_is_not_supported_outside_its_architectures",
    ),
    (
        "MF.04",
        "METRIC_FAMILIES",
        "NOT_SUPPORTED is not zero",
        "test_book6_families.py",
        "test_not_supported_is_not_zero",
    ),
    (
        "MF.05",
        "METRIC_FAMILIES",
        "a scoped definition requires a declared architecture family",
        "test_book6_families.py",
        "test_a_scoped_definition_requires_a_declared_architecture_family",
    ),
    (
        "MF.06",
        "METRIC_FAMILIES",
        "measurement roles remain distinct across families",
        "test_book6_families.py",
        "test_measurement_roles_remain_distinct_across_families",
    ),
)


def rows_for_family(family: str) -> tuple[tuple[str, str, str, str, str], ...]:
    """Every traced row in one family, in declaration order."""

    return tuple(row for row in TRACEABILITY_ROWS if row[1] == family)


#: Canonical invariant: no traceability row may exist without a real assertion.
EVERY_ROW_IS_BOUND_TO_A_REAL_ASSERTION: bool = True


__all__ = [
    "EVERY_ROW_IS_BOUND_TO_A_REAL_ASSERTION",
    "STRUCTURAL_FAMILIES",
    "TRACEABILITY_ROWS",
    "VALIDATION_FAMILIES",
    "rows_for_family",
]
