"""G6 canonical scenario runner (STRESS-G6ER1).

Materializes S20–S24 as canonical scenarios per the Stress Suite Scenario
Catalog execution contract:

    scenario.json            decision-grade fixture + SEALED expectation fields
    initial_epoch.json       starting governance state (contract, authority, seq)
    stimulus_events.jsonl    one JSON stimulus per line, replayed in order
    expected_phase_trace.json SEALED expected phase sequence
    forbidden_transitions.json transitions that must never appear in the trace
    evidence_objects/        evidence records registered in the decision path
    run_receipt.json         generated by this runner (byte-reproducible)
    human_readable_result.md generated by this runner

Sealing law: the DECISION PATH (run_g6_scenario) consumes only the
decision-grade projection — expected_outcome, hidden_ground_truth and
expected_phase_trace are stripped before replay. They are consulted solely by
evaluate_g6_expectation, mirroring the G4/G5 runner split, and the receipt
records expected_outcome_accessed / hidden_ground_truth_accessed = False.

The dispatch is by stimulus EVENT TYPE, never by scenario id: no
`if scenario_id == "S20"` anywhere; every scenario directory drives the same
generic machinery.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .authority import AuthorityState, AuthorityViolation
from .base import deterministic_hex
from .evidence import EvidenceRecord
from .g6_governance import (
    ActionGrantEnvelope,
    ActionRequest,
    AllocatorProvenanceLedger,
    AllocatorProvenanceRecord,
    CapabilityGrant,
    CapabilityGraphEntry,
    ConstitutionalRuleRegistry,
    ConstitutionPermissionRecord,
    EmpiricalEvidenceGrade,
    EvalContractSnapshot,
    EvidenceGraph,
    GovernanceClassificationEvidence,
    GovernanceEvent,
    OperatorMandate,
    apply_capability_change,
    apply_operator_directive,
    attempt_capability_driven_grant,
    activate_future_version,
    classify_governance_event,
    evaluate_against_window,
    execute_under_operator_hold,
    propose_contract_criteria_change,
)
from .registry import EvidenceRegistry, UnknownEvidenceRef

#: governed constitutional rule fixture (G6-TC06) — the smallest bounded
#: representation of the constitutional authority relevant to the G6 scenarios.
_CONSTITUTIONAL_RULES_FIXTURE = (
    Path(__file__).resolve().parent.parent / "fixtures" /
    "g6_constitutional_rules.json")


def _load_constitutional_rules() -> ConstitutionalRuleRegistry:
    data = json.loads(_CONSTITUTIONAL_RULES_FIXTURE.read_text(encoding="utf-8"))
    return ConstitutionalRuleRegistry.from_fixture(data)


class ScenarioStimulusError(Exception):
    """A stimulus was structurally invalid (distinct from an expected refusal)."""


@dataclass
class G6Pack:
    scenario_id: str
    scenario_version: str
    threat_class: str
    dir: Path
    decision: Dict[str, Any]                 # decision-grade fixture
    expected_outcome: str                    # SEALED
    hidden_ground_truth: Dict[str, Any]      # SEALED
    expected_phase_trace: List[Dict[str, Any]]  # SEALED
    forbidden_transitions: List[Dict[str, Any]]

    def decision_grade(self) -> Dict[str, Any]:
        """The ONLY projection the decision path may see."""
        return self.decision


def load_g6_pack(path: Path) -> G6Pack:
    scenario = json.loads((path / "scenario.json").read_text(encoding="utf-8"))
    initial = json.loads((path / "initial_epoch.json").read_text(encoding="utf-8"))
    stimuli = [json.loads(line) for line in
               (path / "stimulus_events.jsonl").read_text(encoding="utf-8").splitlines()
               if line.strip()]
    forbidden = json.loads((path / "forbidden_transitions.json").read_text(
        encoding="utf-8"))["forbidden_transitions"]
    evidence_objects: List[Dict[str, Any]] = []
    ev_dir = path / "evidence_objects"
    if ev_dir.is_dir():
        for p in sorted(ev_dir.glob("*.json")):
            evidence_objects.append(json.loads(p.read_text(encoding="utf-8")))
    decision = {
        "scenario_id": scenario["scenario_id"],
        "scenario_version": scenario["scenario_version"],
        "threat_class": scenario["threat_class"],
        "initial_epoch": initial,
        "stimulus_events": stimuli,
        "evidence_objects": evidence_objects,
    }
    expected_trace = json.loads((path / "expected_phase_trace.json").read_text(
        encoding="utf-8"))["phases"]
    return G6Pack(
        scenario_id=scenario["scenario_id"],
        scenario_version=scenario["scenario_version"],
        threat_class=scenario["threat_class"],
        dir=path,
        decision=decision,
        expected_outcome=scenario["expected_outcome"],
        hidden_ground_truth=scenario.get("hidden_ground_truth", {}),
        expected_phase_trace=expected_trace,
        forbidden_transitions=forbidden,
    )


# --------------------------------------------------------------------------- #
# Replay state
# --------------------------------------------------------------------------- #
@dataclass
class _ReplayState:
    seq: int
    authority: AuthorityState
    registry: EvidenceRegistry
    rules: ConstitutionalRuleRegistry
    contracts: Dict[str, EvalContractSnapshot] = field(default_factory=dict)
    candidates: Dict[str, Any] = field(default_factory=dict)
    capability: Dict[str, CapabilityGraphEntry] = field(default_factory=dict)
    evidence_graph: EvidenceGraph = field(default_factory=EvidenceGraph)
    mandates: Dict[str, OperatorMandate] = field(default_factory=dict)
    permissions: Dict[str, ConstitutionPermissionRecord] = field(default_factory=dict)
    grants: Dict[str, ActionGrantEnvelope] = field(default_factory=dict)
    hold_active_since: Optional[int] = None
    last_candidate_id: str = ""
    allocator_ledger: AllocatorProvenanceLedger = field(
        default_factory=AllocatorProvenanceLedger)


def _register_evidence(state: _ReplayState, objects: List[Dict[str, Any]]) -> None:
    for obj in objects:
        state.registry.register(EvidenceRecord(
            record_id=obj["record_id"],
            kind=obj.get("kind", "OBSERVATION"),
            claim=obj.get("claim", ""),
            source_lineage=obj.get("source_lineage", ""),
            allocator=obj.get("allocator", ""),
            retrieval_lineage=obj.get("retrieval_lineage", ""),
            subject=obj.get("subject", ""),
            seq=int(obj.get("seq", 0)),
        ))





def _refusal(phase: str, detail: Dict[str, Any]) -> Dict[str, Any]:
    return {"phase": phase, "detail": detail}


def _apply_stimulus(state: _ReplayState, ev: Dict[str, Any]) -> Dict[str, Any]:
    """Generic event-type dispatch. Returns one observed phase entry. Expected
    refusals are CAPTURED phases (the shortcut was attempted and refused);
    structurally invalid stimuli raise ScenarioStimulusError."""
    etype = ev.get("type")
    if not etype:
        raise ScenarioStimulusError("stimulus event missing 'type'")

    # ---- S20: evaluation-contract lifecycle ------------------------------ #
    if etype == "freeze_evaluation_contract":
        snap = EvalContractSnapshot.freeze(
            contract_id=ev["contract_id"], window_seq=int(ev["window_seq"]),
            criteria=ev["criteria"], created_by=ev.get("created_by", "GOVERNOR"))
        state.contracts[ev["contract_id"]] = snap
        return {"phase": "CONTRACT_FROZEN",
                "detail": {"contract_id": ev["contract_id"],
                           "window_seq": snap.window_seq,
                           "criteria_fingerprint": snap.criteria_fingerprint,
                           "deep_frozen": snap.is_deeply_frozen()}}

    if etype == "mutate_active_criteria":
        snap = state.contracts[ev["contract_id"]]
        try:
            snap.mutate_criteria(ev["key"], ev["value"])
        except ValueError as exc:
            return _refusal("MUTATION_REFUSED",
                            {"contract_id": ev["contract_id"],
                             "reason": str(exc)})
        raise ScenarioStimulusError("frozen contract mutation unexpectedly succeeded")

    if etype == "nested_mutation_attempt":
        snap = state.contracts[ev["contract_id"]]
        node: Any = snap.criteria
        try:
            for key in ev["path"][:-1]:
                node = node[key]
            last = ev["path"][-1]
            if isinstance(node, dict):
                node[last] = ev["value"]
            else:
                getattr(node, ev.get("method", "append"))(ev["value"])
        except (TypeError, AttributeError, IndexError, KeyError) as exc:
            return _refusal("NESTED_MUTATION_IMPOSSIBLE",
                            {"contract_id": ev["contract_id"],
                             "path": ev["path"], "reason": str(exc)})
        raise ScenarioStimulusError(
            f"nested mutation unexpectedly succeeded: {ev['path']}")

    if etype == "propose_future_criteria":
        snap = state.contracts[ev["contract_id"]]
        base_fp = ev["base_fingerprint"]
        if base_fp == "CURRENT":   # symbolic ref to the live snapshot fingerprint
            base_fp = snap.criteria_fingerprint
        verdict = propose_contract_criteria_change(
            snap, ev["criteria"], base_fingerprint=base_fp,
            seq=int(ev["target_window_seq"]), proposed_by=ev.get("proposed_by", "GOVERNOR"),
            proposal_evidence_ref=ev.get("proposal_evidence_ref", ""))
        if verdict.candidate is not None:
            state.candidates[verdict.candidate.candidate_id] = verdict.candidate
            state.last_candidate_id = verdict.candidate.candidate_id
        return {"phase": verdict.status,
                "detail": {"proposal_id": verdict.proposal_id,
                           "target_window_seq": verdict.target_window_seq,
                           "retroactive": verdict.retroactive,
                           "rationale": verdict.rationale}}

    if etype == "attempt_contract_activation":
        cid = ev["candidate_id"]
        if cid == "CAND_1":        # symbolic ref to the most recent PROPOSED candidate
            cid = getattr(state, "last_candidate_id", "")
        candidate = state.candidates[cid]
        ratifier = ev["ratifier"]
        try:
            verdict = activate_future_version(
                candidate, state.authority, ratifier=ratifier,
                seq=int(ev["seq"]))
        except AuthorityViolation as exc:
            return _refusal("ACTIVATION_REFUSED",
                            {"candidate_id": cid,
                             "ratifier": ratifier, "reason": str(exc)})
        state.contracts[f"{candidate.contract_id}@{candidate.target_window_seq}"] = \
            verdict.activated_snapshot
        return {"phase": verdict.status,
                "detail": {"candidate_id": candidate.candidate_id,
                           "activated_window_seq": verdict.activated_snapshot.window_seq,
                           "authority_basis": verdict.activated_snapshot.authority_basis}}

    if etype == "evaluate_result":
        snap = state.contracts[ev["contract_id"]]
        w = evaluate_against_window(snap, ev["result_id"],
                                    observed_metric=float(ev["observed_metric"]))
        return {"phase": "WINDOW_EVALUATION",
                "detail": {**w.to_dict()}}

    # ---- S21: capability vs authority ------------------------------------ #
    if etype == "capability_change":
        cap = state.capability.get(ev["worker_id"], CapabilityGraphEntry(
            worker_id=ev["worker_id"]))
        out = apply_capability_change(cap, ev["new_reliability_grade"])
        state.capability[ev["worker_id"]] = CapabilityGraphEntry(
            worker_id=ev["worker_id"],
            reliability_grade=out.reliability_after,
            capability_evidence_refs=(ev.get("evidence_ref", ""),))
        return {"phase": "CAPABILITY_UPDATED",
                "detail": {**out.to_dict()}}

    if etype == "attempt_authority_grant":
        try:
            grant = attempt_capability_driven_grant(
                state.authority, requester=ev["requester"],
                target_actor=ev["target_actor"],
                requested_risk_class=ev["risk_class"], seq=int(ev["seq"]))
        except AuthorityViolation as exc:
            return _refusal("GRANT_REFUSED",
                            {"requester": ev["requester"],
                             "target_actor": ev["target_actor"],
                             "risk_class": ev["risk_class"], "reason": str(exc)})
        return {"phase": "GRANT_ISSUED",
                "detail": {"grant_id": grant.grant_id}}

    # ---- S22: operator directive / evidence grades ------------------------ #
    if etype == "define_permission":
        rec = ConstitutionPermissionRecord.claim(
            rule_ref=ev["rule_ref"],
            permitted_action_class=ev["permitted_action_class"],
            basis=ev["basis"], seq=int(ev.get("seq", 0)),
            provenance=ev.get("provenance", "scenario-stimulus"))
        try:
            verified = rec.verify(state.rules)
        except ValueError as exc:
            return _refusal("PERMISSION_CLAIM_UNVERIFIED",
                            {"permission_id": ev["permission_id"],
                             "rule_ref": ev["rule_ref"], "reason": str(exc)})
        state.permissions[ev["permission_id"]] = verified
        return {"phase": "PERMISSION_RECORDED",
                "detail": {**verified.to_dict(),
                           "permission_id": ev["permission_id"]}}

    if etype == "grant_operator_mandate":
        mandate = OperatorMandate(
            actor=ev["actor"], scope=ev["scope"], issued_by=ev["issued_by"],
            grant_ref=ev["grant_ref"], seq=int(ev["seq"]))
        state.mandates[ev["actor"]] = mandate
        return {"phase": "MANDATE_RECORDED",
                "detail": {**mandate.to_dict(),
                           "note": "claim recorded; verification happens at directive time against canonical authority"}}

    if etype == "governed_grant_issue":
        # canonical capability grant issued via propose+ratify (G6-TC05):
        # the grant must PRE-EXIST any mandate/directive that references it.
        grant = CapabilityGrant(
            grant_id=ev["grant_id"], actor=ev["actor"], action=ev["action"],
            target=ev["target"], environment=ev.get("environment", "local-test"),
            risk_class=ev.get("risk_class", "read"),
            issued_by=ev["issued_by"], issued_seq=int(ev["seq"]))
        try:
            state.authority.propose_authority_change(
                ev.get("proposer", grant.actor), grant.actor, grant)
            state.authority.ratify_authority_change(
                ev["issued_by"], ev.get("proposer", grant.actor), grant.actor, grant)
        except AuthorityViolation as exc:
            return _refusal("GOVERNED_GRANT_REFUSED",
                            {"grant_id": ev["grant_id"], "reason": str(exc)})
        return {"phase": "GOVERNED_GRANT_ISSUED",
                "detail": {"grant_id": grant.grant_id, "actor": grant.actor,
                           "issued_by": grant.issued_by,
                           "risk_class": grant.risk_class,
                           "issued_seq": grant.issued_seq}}

    if etype == "operator_directive":
        perm = state.permissions[ev["permission_id"]]
        mandate = state.mandates.get(ev.get("mandate_for", ""))
        out = apply_operator_directive(
            directive_id=ev["directive_id"],
            actor=ev["actor"],
            authority=state.authority,
            graph=state.evidence_graph,
            permission=perm,
            evidence_id=ev.get("evidence_id", ""),
            mandate=mandate,
            operator_preference=ev.get("operator_preference", ""),
            claimed_level=ev.get("claimed_level", ""))
        return {"phase": "DIRECTIVE_AUTHORIZED" if out.operator_action_authorized
                else "DIRECTIVE_REFUSED",
                "detail": {**out.to_dict()}}

    if etype == "evidence_grade_change":
        try:
            state.evidence_graph = state.evidence_graph.with_grade(
                ev["evidence_id"], ev["new_grade"], ev["ref"], state.registry,
                subject=ev.get("subject", ev["evidence_id"]))
        except (ValueError, UnknownEvidenceRef) as exc:
            return _refusal("GRADE_CHANGE_REFUSED",
                            {"evidence_id": ev["evidence_id"],
                             "new_grade": ev["new_grade"], "reason": str(exc)})
        return {"phase": "GRADE_CHANGED",
                "detail": {"evidence_id": ev["evidence_id"],
                           "new_grade": ev["new_grade"],
                           "grade_now": state.evidence_graph.grade_of(ev["evidence_id"])}}

    # ---- S23: operator unavailable / action envelopes --------------------- #
    if etype == "issue_action_grant":
        grant = ActionGrantEnvelope(
            grant_id=ev["grant_id"], grantee=ev["grantee"], action=ev["action"],
            target_scope=ev["target_scope"],
            affected_surface=ev.get("affected_surface", "REVERSIBLE_SANDBOX"),
            reversible=bool(ev.get("reversible", True)),
            risk_class=ev.get("risk_class", "local-write"),
            environment=ev.get("environment", "local-test"),
            issued_seq=int(ev["issued_seq"]),
            expiry_seq=int(ev.get("expiry_seq", 0)),
            status=ev.get("status", "ACTIVE"),
            authority_basis=ev.get("authority_basis", ""))
        state.grants[grant.grant_id] = grant
        return {"phase": "ACTION_GRANT_RECORDED",
                "detail": {**grant.to_dict()}}

    if etype == "revoke_action_grant":
        grant = state.grants[ev["grant_id"]]
        state.grants[ev["grant_id"]] = ActionGrantEnvelope(
            grant_id=grant.grant_id, grantee=grant.grantee, action=grant.action,
            target_scope=grant.target_scope,
            affected_surface=grant.affected_surface, reversible=grant.reversible,
            risk_class=grant.risk_class, environment=grant.environment,
            issued_seq=grant.issued_seq, expiry_seq=grant.expiry_seq,
            status="REVOKED", authority_basis=grant.authority_basis)
        return {"phase": "ACTION_GRANT_REVOKED",
                "detail": {"grant_id": grant.grant_id}}

    if etype == "operator_unavailable":
        state.hold_active_since = int(ev["seq"])
        return {"phase": "OPERATOR_UNAVAILABLE",
                "detail": {"seq": int(ev["seq"])}}

    if etype == "request_action":
        grant = state.grants.get(ev.get("grant_id", ""))
        req = ActionRequest(
            action=ev["action"], target_scope=ev["target_scope"],
            affected_surface=ev.get("affected_surface", "REVERSIBLE_SANDBOX"),
            reversible=bool(ev.get("reversible", True)),
            risk_class=ev.get("risk_class", "local-write"),
            environment=ev.get("environment", "local-test"))
        verdict = execute_under_operator_hold(
            action_id=ev["action_id"], actor=ev["actor"], request=req,
            grant=grant, current_seq=int(ev["current_seq"]))
        return {"phase": verdict.verdict,
                "detail": {**verdict.to_dict(),
                           "requested_action": req.to_dict()}}

    # ---- S24: governance classification ----------------------------------- #
    if etype == "classify_governance_event":
        ce = [GovernanceClassificationEvidence(
            proposed_channel=c["proposed_channel"],
            evidence_refs=tuple(c.get("evidence_refs", ())),
            status=c.get("status", "SUPPORTED"),
            binding=c.get("binding", ""),
            scope=c.get("scope", ""))
            for c in ev.get("classification_evidence", ())]
        event = GovernanceEvent(
            event_id=ev["event_id"], raw_event=ev.get("raw_event", ""),
            evidence_refs=tuple(ev.get("evidence_refs", ())),
            consequence_class=ev.get("consequence_class", ""),
            authority_context=ev.get("authority_context", ""),
            containment_action=ev.get("containment_action", "SAFE_HOLD"),
            seq=int(ev.get("seq", 0)),
            binding=ev.get("binding", ""),
            scope=ev.get("scope", ""))
        d = classify_governance_event(event, ce, registry=state.registry)
        return {"phase": d.channel,
                "detail": {**d.to_dict()}}

    # ---- ER07: allocator provenance ---------------------------------------- #
    if etype == "record_allocator_provenance":
        rec = AllocatorProvenanceRecord(
            evidence_ref=ev["evidence_ref"],
            initiating_actor=ev["initiating_actor"],
            allocator_actor=ev["allocator_actor"],
            worker_selected=ev.get("worker_selected", ""),
            source_path=ev.get("source_path", ""),
            retrieval_lineage=ev.get("retrieval_lineage", ""),
            exposure_lineage=ev.get("exposure_lineage", ""),
            seq=int(ev.get("seq", 0)))
        state.allocator_ledger.record(rec)
        return {"phase": "ALLOCATOR_PROVENANCE_RECORDED",
                "detail": {**rec.to_dict()}}

    if etype == "observe_allocator_concentration":
        report = state.allocator_ledger.allocator_concentration()
        return {"phase": "ALLOCATOR_CONCENTRATION_OBSERVED",
                "detail": report}

    raise ScenarioStimulusError(f"unknown stimulus event type {etype!r}")


# --------------------------------------------------------------------------- #
# Run + evaluate
# --------------------------------------------------------------------------- #
@dataclass
class G6ScenarioResult:
    scenario_id: str
    phases: List[Dict[str, Any]]
    behavior_fingerprint: str
    forbidden_shortcuts_attempted: List[str]
    forbidden_shortcuts_refused: List[str]
    artifacts: Dict[str, Any] = field(default_factory=dict)


def run_g6_scenario(decision: Dict[str, Any]) -> G6ScenarioResult:
    state = _ReplayState(
        seq=int(decision["initial_epoch"].get("seq", 0)),
        authority=AuthorityState(),
        registry=EvidenceRegistry(),
        rules=_load_constitutional_rules())
    for actor, level in decision["initial_epoch"].get("authority_seed", {}).items():
        state.authority.seed_level(actor, level)
    state.authority.freeze_initialization()
    _register_evidence(state, decision.get("evidence_objects", []))

    phases: List[Dict[str, Any]] = []
    for ev in decision["stimulus_events"]:
        phase = _apply_stimulus(state, ev)
        phase["seq"] = len(phases) + 1
        phases.append(phase)

    attempted = [p["phase"] for p in phases if p["phase"].endswith("_REFUSED")
                 or p["phase"] in ("NESTED_MUTATION_IMPOSSIBLE", "OPERATOR_HOLD",
                                   "UNRESOLVED_GOVERNANCE_EVENT")]
    behavior_fingerprint = deterministic_hex(
        "g6_scenario_behavior",
        json.dumps([{"phase": p["phase"], "detail": p["detail"]}
                    for p in phases], sort_keys=True, separators=(",", ":")),
        length=32)
    return G6ScenarioResult(
        scenario_id=decision["scenario_id"], phases=phases,
        behavior_fingerprint=behavior_fingerprint,
        forbidden_shortcuts_attempted=sorted(set(attempted)),
        forbidden_shortcuts_refused=sorted(set(attempted)),
        artifacts={"allocator_concentration":
                   state.allocator_ledger.allocator_concentration(),
                   "authority_event_summary":
                   state.authority.authority_event_summary()})


def evaluate_g6_expectation(res: G6ScenarioResult, pack: G6Pack) -> Dict[str, Any]:
    """Sealed-field comparison ONLY — never consulted by the decision path."""
    observed = [p["phase"] for p in res.phases]
    expected = [p["phase"] for p in pack.expected_phase_trace]
    failures: List[str] = []
    if observed != expected:
        failures.append(
            f"phase trace mismatch: observed={observed} expected={expected}")
    forbidden_names = {t["transition"] for t in pack.forbidden_transitions}
    leaked = forbidden_names & set(observed)
    if leaked:
        failures.append(f"forbidden transitions appeared: {sorted(leaked)}")
    if not res.forbidden_shortcuts_attempted:
        failures.append("scenario did not attempt any forbidden shortcut")
    return {"pass": not failures, "failures": failures,
            "actual_outcome": "PASS_G6_SCENARIO" if not failures
            else "FAIL_G6_SCENARIO"}


def build_receipt(pack: G6Pack, res: G6ScenarioResult,
                  verdict: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "scenario_id": pack.scenario_id,
        "scenario_version": pack.scenario_version,
        "threat_class": pack.threat_class,
        "behavior_fingerprint": res.behavior_fingerprint,
        "expected_outcome": pack.expected_outcome,
        "actual_outcome": verdict["actual_outcome"],
        "pass": verdict["pass"],
        "failures": verdict["failures"],
        "phases": [{"phase": p["phase"], "seq": p["seq"]} for p in res.phases],
        "forbidden_transitions_declared": [t["transition"]
                                           for t in pack.forbidden_transitions],
        "forbidden_shortcuts_attempted": res.forbidden_shortcuts_attempted,
        "forbidden_shortcuts_refused": res.forbidden_shortcuts_refused,
        "allocator_concentration": res.artifacts["allocator_concentration"],
        "expected_outcome_accessed": False,
        "hidden_ground_truth_accessed": False,
        "authority_accounting": {
            "external_authority_mutations": 0,
            "production_authority_mutations": 0,
            "scenario_internal_authority_events":
                res.artifacts.get("authority_event_summary", {}),
            "note": ("scenario-internal AuthorityState objects are SIMULATED "
                     "transitions inside the scenario; they are not external "
                     "or production authority mutations"),
        },
        "cloud_mutations": 0,
        "production_mutations": 0,
        "capital_mutations": 0,
        "model_calls": 0,
    }


def human_result(receipt: Dict[str, Any]) -> str:
    lines = [
        f"# {receipt['scenario_id']} — G6 scenario result",
        "",
        f"- outcome: **{receipt['actual_outcome']}** "
        f"(expected `{receipt['expected_outcome']}`)"
        + (" — PASS" if receipt["pass"] else f" — FAIL {receipt['failures']}"),
        f"- behavior fingerprint: `{receipt['behavior_fingerprint']}`",
        f"- forbidden transitions declared: "
        f"{receipt['forbidden_transitions_declared']}",
        f"- forbidden shortcuts attempted & refused: "
        f"{receipt['forbidden_shortcuts_attempted']}",
        f"- sealed: expected_accessed={receipt['expected_outcome_accessed']} · "
        f"hidden_ground_truth_accessed={receipt['hidden_ground_truth_accessed']}",
        f"- authority accounting: external mutations "
        f"{receipt['authority_accounting']['external_authority_mutations']} · "
        f"production {receipt['authority_accounting']['production_authority_mutations']} · "
        f"scenario-internal events "
        f"{receipt['authority_accounting']['scenario_internal_authority_events']['total']} "
        f"(simulated only) · model calls: {receipt['model_calls']} · "
        f"cloud/production/capital mutations: "
        f"{receipt['cloud_mutations']}/{receipt['production_mutations']}/"
        f"{receipt['capital_mutations']}",
        "",
        "## Phase trace",
        "",
    ]
    for p in receipt["phases"]:
        lines.append(f"- `{p['seq']:02d}` {p['phase']}")
    return "\n".join(lines) + "\n"
