"""Generate LF3 governance and closeout artifacts."""
from __future__ import annotations
import pandas as pd
import lf3_common as C

def write_csv(name, rows):
    pd.DataFrame(rows).to_csv(C.RESULTS / name, index=False)

def main():
    write_csv("20_TRADEABILITY_REQUIREMENT_PLACEHOLDER.csv", [
        {"node":"deep-rank downside reversal","statistical_validity":"VALIDATED_DESCRIPTIVE","executability_status":"NOT_YET_AUDITED","theoretical_requirement":"UNKNOWN / instrument and shortability audit required","note":"No trade or instrument availability claim"},
        {"node":"cross-field breadth gate","statistical_validity":"VALIDATED_CONDITIONAL_L1","executability_status":"NOT_YET_AUDITED","theoretical_requirement":"UNKNOWN","note":"State/context role only"},
        {"node":"isolated-down rebound topology","statistical_validity":"LOCAL_NODE_LIMITED_BY_ISOLATED_N","executability_status":"NOT_YET_AUDITED","theoretical_requirement":"UNKNOWN","note":"No directional execution design"},
        {"node":"SHHM continuation geometry","statistical_validity":"DESCRIPTIVE_ONLY","executability_status":"NOT_YET_AUDITED","theoretical_requirement":"UNKNOWN","note":"Not an alpha"},
    ])
    write_csv("21_ALPHA_ROLE_REGISTRY.csv", [
        {"node":"DEPTH_TAIL_GRADIENT","sample":"3.29M panel rows","effect":"7D normalized tail rises with rank depth across all states","confidence":"HIGH descriptive","conditionality":"rank depth / volatility","rank_scope":"501-2000","causal_level":"L0","failure_modes":"scale and liquidity composition","future_role":"STRUCTURAL_STATE / DISTRIBUTION"},
        {"node":"DEEP_DOWNSIDE_REVERSAL","sample":"~7k 30D-purged 3s down events","effect":"1501-2000 P(rev7) ~.58, giveback materially larger than shallow","confidence":"HIGH purge-stable","conditionality":"sign, depth, participation","rank_scope":"501-2000","causal_level":"L0","failure_modes":"censoring, local sample","future_role":"REVERSAL / DISTRIBUTION"},
        {"node":"BREADTH_DELIVERY_GATE","sample":"2095 daily observations per band + event panel","effect":"breadth level remains positive after BTC/vol controls; high breadth raises delivery","confidence":"MEDIUM-HIGH","conditionality":"global breadth + local dispersion","rank_scope":"501-2000","causal_level":"L1/L2 candidate","failure_modes":"observational confounding; lag stability pending","future_role":"CROSS_FIELD_GATE / REGIME_FILTER"},
        {"node":"ISOLATED_SHOCK_TOPOLOGY","sample":"1025 isolated downside >=2s; 307 isolated downside >=3s","effect":"isolated downside shocks are local and rebound-prone; deepest cells thin","confidence":"MEDIUM","conditionality":"participation topology","rank_scope":"501-2000","causal_level":"L0","failure_modes":"small isolated N","future_role":"LOCAL_CLUSTER / REVERSAL"},
        {"node":"SHHM_VS_SHMC","sample":"large four-state comparison","effect":"SHHM has higher normalized tail than SHMC; SHMC is reversion-like","confidence":"MEDIUM","conditionality":"momentum alignment","rank_scope":"501-2000","causal_level":"L0","failure_modes":"no future mechanism claim","future_role":"CONTINUATION / DISTRIBUTION"},
        {"node":"RANK_HEALTH_BRIDGE","sample":"isolated >=3s downside events","effect":"rank deterioration/improvement coordinates compared descriptively","confidence":"QUEUED","conditionality":"pre-event rank velocity","rank_scope":"501-2000","causal_level":"L0","failure_modes":"no MECH-7 context needed for core; no death label","future_role":"RANK_HEALTH / DECAY_CONTEXT"},
    ])
    write_csv("22_CAUSALITY_LADDER.csv", [
        {"claim":"same-day neighborhood and participation anatomy","level":"L0 DESCRIPTIVE_CO_MOVEMENT","status":"earned","note":"No temporal causation"},
        {"claim":"deep-rank downside reversal","level":"L0","status":"earned","note":"Forward ordering is descriptive, not causal"},
        {"claim":"Top-500 breadth to lower tail delivery","level":"L1 TEMPORAL_ORDERING / L2 CONDITIONAL_LEAD_LAG CANDIDATE","status":"limited","note":"Explicit multi-lag/subperiod confirmation remains queued"},
        {"claim":"triangle breadth-dispersion-tail","level":"L0/L1","status":"associational","note":"Partial correlation pilot only"},
        {"claim":"sector/chain mechanism","level":"NULL","status":"not earned","note":"LF2 residual null"},
    ])
    write_csv("23_PROMOTE_MERGE_DISSOLVE.csv", [
        {"node":"DEPTH_TAIL_GRADIENT","verdict":"PROMOTE","basis":"all momentum states show depth gradient; re-scoped from SHMC"},
        {"node":"DEEP_DOWNSIDE_REVERSAL","verdict":"PROMOTE","basis":"30D purge-stable monotonic sign x rank geometry"},
        {"node":"BREADTH_DISPERSION_DELIVERY","verdict":"PROMOTE","basis":"high breadth + high dispersion sequence clears >=50 / >=3-period rule"},
        {"node":"ISOLATED_SHOCK_TOPOLOGY","verdict":"LOCAL_NODE","basis":"strong but deepest isolated N thin"},
        {"node":"COORDINATED_UP_GIVEBACK","verdict":"LOCAL_NODE","basis":"coordinated-up outcome map is descriptive, not directional"},
        {"node":"SHMC_HIGH_TAIL","verdict":"DISSOLVE","basis":"SHMC lower tail than SHHM at every band"},
        {"node":"SECTOR_CHAIN_RESIDUAL","verdict":"MERGE/NULL","basis":"LF2 residual sector/chain null"},
        {"node":"MECH7_CONTEXT","verdict":"QUEUED","basis":"not used in LF3 core; stable date-keyed join schema preserved"},
    ])
    write_csv("24_NULL_AND_FAILED_RESULTS.csv", [
        {"result":"single master isolation score","verdict":"NOT_BUILT","reason":"neighborhood families are incomplete; no unjustified compression"},
        {"result":"DTW/k-medoids outcome clusters","verdict":"DESCRIPTIVE_ONLY","reason":"rule-based path families used; formal clustering requires robustness audit"},
        {"result":"sector/chain residual","verdict":"NULL","reason":"carried LF2 residual sector/chain null"},
        {"result":"SHMC-specific tail activation","verdict":"DISSOLVED","reason":"SHMC is lowest-tail state; depth effect is shared"},
        {"result":"isolated deep-rank cells","verdict":"DATA_LIMITED","reason":"effective isolated counts are thin"},
        {"result":"MECH-7 context reuse","verdict":"QUEUED","reason":"not required for core generation; date-keyed schema retained for future alignment"},
        {"result":"tradeability/execution","verdict":"NOT_AUDITED","reason":"explicitly out of scope"},
    ])
    summary = """# LOWER-FIELD-3 SUMMARY\n\nLF3 moves from endpoint reversal rates to local event anatomy while preserving the LF2 integrity repair and its restrictions.\n\n## Main findings\n\n- A contextual lonely dump is a same-band >=2-sigma downside event with exactly one same-sign >=2-sigma mover in that band/date. Rank-window neighbors are computed with a causal same-date PIT join. Behavioral, correlation, and state neighborhoods remain schema-reserved because no validated fixed peer map is present in LF2. No master isolation score was invented.\n- Isolated 3-sigma downside events are disproportionately temporary shocks: the path map shows stronger 7D reversal/recovery than coordinated events. Deepest isolated cells are thin, so this is a LOCAL_NODE, not a universal rule.\n- Coordinated upside events (`BAND_BROAD_UP`/`MULTI_BAND_UP`) are synchronized and tend toward giveback; continuation/exhaustion divergence is descriptive only.\n- The reversal state machine makes 1-sigma recovery explicit. Recovery, 25/50-percent giveback, full reversal, and new-extreme states are competing event-time observations, not a sequential signal.\n- The LF2 SHMC correction survives: `SHORT_HOT_MEDIUM_HOT` has higher normalized tail probability than SHMC. SHMC-specific activation is dissolved; medium-horizon alignment is a continuation/reversion geometry candidate only.\n- Rank deterioration is retained as a queued rank-health bridge; no death/extinction label is assigned.\n- `BRD_HI + DISP_HI` is the repeated local state with >=50 effective observations and >=3 periods. It raises next-day tail-delivery activity and is consistent with the LF2 breadth gate.\n- The basket implementation is descriptive cohort geometry only. The triangle pilot treats A=Top-500 breadth, B=lower dispersion, C=tail share as one higher-order dependency; no universal mediation claim is made.\n\n## Interpretation\n\nThe lower field changes form with participation: isolated downside shocks are local and rebound-prone, whereas coordinated upside is broad and giveback-prone. This is a participation-topology node, not a trading instruction. Center coupling and tail localization from LF1/LF2 remain intact.\n\n## Limits\n\nMECH-7 was available in the repository but was not consumed by LF3 core generation; the output schema preserves a date-keyed join path so context can be attached later without regenerating core events. Formal behavioral/correlation neighbor maps, 60D censoring, stable trajectory clustering, and execution/tradability audits are not earned. All claims are L0, except breadth-to-delivery as an L1/L2 candidate.\n\n`human_review_required = TRUE`  \n`next_checkpoint_authorized = FALSE`\n"""
    (C.ROOT / "25_LOWER_FIELD_3_SUMMARY.md").write_text(summary, encoding="utf-8")
    decision = """# LOWER-FIELD-3 DECISION\n\n## Verdict\n\n**PASS_LOWER_FIELD_3_LOCAL_EVENT_ANATOMY_WITH_LIMITATIONS**\n\nLF3 earns a local anatomy checkpoint because isolated-down and coordinated-up participation topologies show distinct, reproducible descriptive path shapes, the deep downside reversal remains purge-stable, and the `BRD_HI|DISP_HI` state clears the local-sequence minimum rule.\n\n## Promoted / local / dissolved\n\n- **PROMOTION_CANDIDATE:** `DEEP_DOWNSIDE_REVERSAL`, `DEPTH_TAIL_GRADIENT` (re-scoped from SHMC), and `BREADTH_DISPERSION_DELIVERY`.\n- **LOCAL_NODE:** `ISOLATED_SHOCK_TOPOLOGY`, `COORDINATED_UP_GIVEBACK`, `SHHM_VS_SHMC` continuation/reversion geometry, `LOCAL_BASKET_GEOMETRY`.\n- **DISSOLVE:** SHMC-specific high-tail activation; no master isolation score; any implied death label.\n- **NULL / QUEUED:** residual sector/chain organization remains null; MECH-7 context reuse, full correlation/behavioral neighborhoods, and extinction/decay are queued.\n\n## Answers to final questions\n\n1. Lonely dump = one same-band same-sign >=2-sigma event, with rank-window neighbor residual retained.\n2. All loners in the generated sample are downside by construction; the 3-sigma subset shows recovery/reversal, but thin deepest isolated N limits confidence.\n3. Only two rule-based loner path families clear >=50 events and >=3 quarters; formal unsupervised clustering is not claimed.\n4. Early 1-sigma recovery is the clearest temporary-shock checkpoint in the current anatomy; pre-event discriminators remain L0.\n5. Rank-neighbor context refines isolation materially; other peer families are schema-ready but not validated from LF2.\n6. 1-sigma recovery is a meaningful descriptive stabilization marker, not an executable rule.\n7. Reversal is staged through recovery, giveback, and competing full-reversal/new-extreme paths.\n8. Coordinated-up outcomes tend toward giveback; continuation is not promoted directionally.\n9. Sign x participation topology survives as a local descriptive node, subject to controls in future work.\n10. Rank deterioration is queued as a rank-health bridge, not structural weakness.\n11. SHHM is higher-tail/continuation-like than SHMC; SHMC is reversion-like; this remains descriptive.\n12. High breadth + high dispersion is the asset-level state with the strongest tail-delivery enrichment.\n13. Triangle pilot is associational and limited; it does not establish mediation or synergy.\n14. Subtle-node audit preserves breadth gate, deep reversal, liquidity/rank-health candidates, and dissolves SHMC rescue.\n15. Future tradability audit is required for every candidate; current status is NOT_YET_AUDITED.\n16. Mature enough for future alpha staging: distribution/reversal roles and cross-field/regime roles only, after human review.\n\n`human_review_required = TRUE`  \n`next_checkpoint_authorized = FALSE`  \n`NO STRATEGY · NO PNL · NO EXECUTION`\n"""
    (C.ROOT / "26_LOWER_FIELD_3_DECISION.md").write_text(decision, encoding="utf-8")
    print("LF3 final artifacts written")
if __name__=="__main__": main()
